### ISSUE TITLE
Update Fck Editor

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#1]
Update editor to the latest version

**Comment by pixeline** [comment]
I suggest using CKEditor, instead of FCKEditor

**Comment by soonick** [comment]
I am not very familiar with either of those, but I will check them out and if CKEditor is better and is still being developed I will do the change.
Thank you.

**Comment by soonick** [comment]
Hello pixeline,

Can you remind me why we wanted to change or update the current editor?

**Comment by armitage** [comment]
For clarification: FCKeditor has been renamed to CKEditor with version 3.0

**Comment by armitage** [comment]
I'm working on upgrading to CKEditor in pommo right now and will issue a pull request when ready.

**Comment by soonick** [comment]
Great,

I will mark this issue as assigned.

**Comment by micdech** [comment]
Hi all,
CKEditor is great, but it have a different license for companies... The issue is relevant! For example: if companies want to use pommo?

I don't think use CKEditor is a good idea...
Otherwise what do you think about TinyMCE? LGPL

**Comment by soonick** [comment]
Hello Michele,

Thanks for pointing that out. I agree with you. We shouldn't use CKEditor if it is not free for companies. We will have to find another option.

TinyMCE may be a good option

**Comment by micdech** [comment]
Hi Adrian,

Maybe i'm wrong... The commercial license is necessary for a commercial project. For company who want to create a commercial project. But PoMMo isn't it, And maybe we can use CKEditor freely...

Perhaps, seems also tinymce have a commercial license...

TinyMCE was chosen by facebook (and Wordpress) and many more.
CKEditor instead by MailChimp and other...

however, the choice can be made freely

**Comment by soonick** [comment]
Hello Michele,

I took a some time to investigate about licenses and this is what I found:

poMMo is GPL
CKEditor is GPL, LGPL and MPL
Tinymce is LGPL

This means that the biggest restriction for which editor we can use are not the editors but poMMo itself. If I understood well GPL is said to be viral, because all the code that touches poMMo has to be open source too. Since both CKEditor and Tinymce are open source then we wouldn't have any problem using them.

LGPL license allows you to use a piece of software (code) in a project that is not open source. An example of this would be integrating CKEditor of Tinymce in your personal website. You don't want to open source the code to your personal website, and because they use LGPL you don't have to.

If I am correct (if someone knows I am wrong please tell me) then the decision of which WYSISYG editor can be made based on which one we feel fits our need better.

Thanks,
Adrian

**Comment by micdech** [comment]
Hi Adrian,
I agree with you. both editors are usable with pommo. Also because what software will use pommo, then will be GPL probabily.

Then you can proceed by replacing FCK with CK Editor :)

Regards
Michele

**Comment by Renegades** [comment]
;-) @ micdech
/\* TinyMCE was chosen by facebook (and Wordpress) and many more */
That's why. Who'd be interested following the Facebook steps anyway? (what is it?) ;-)

Na, you wouldn't have any license issue for using CKEditor on a commercial site as long a you use it for your own usage!

**Comment by micdech** [comment]
Jajajaja :D

No i couldn't be a new Zuckerberg! I haven't this skills! :) But...in the feature, if any company can use pommo...maybe they can support it with a donations...And it's possible only if they can use it on commercial scope...

I hope that i've explained well :)

Best regards

**Comment by soonick** [comment]
The new editor has been implemented.
