### ISSUE TITLE
logout timeout

### ISSUE THREAD

**Issue by latsami** [soonick/poMMo#101]
Hello,
we installed Pommo for a new client who makes bigger newsletters than our former clients. She spent more than an hour to prepare her mail, and when she wanted to save her template, she was asked to log in again, but then there's an error and the template was gone.
Is it possible to modify the duration of the logout timeout?
Thanks

**Comment by soonick** [comment]
Hello latsami,

The time it takes a PHP session to expire is a server configuration, it is not particular to poMMo.

You can change this value on your php.ini file with the session.cookie_lifetime directive or you can modify the bootstrap file to include this line:

ini_set("session.cookie_lifetime","3600");

The second argument is the number of seconds before the session expires.
