### ISSUE TITLE
long e-mail subject.

### ISSUE THREAD

**Issue by msd101psu** [soonick/poMMo#104]
I created a mailing with a subject longer than 60 characters.  The test page and send page throw a SQL error since the mailing table subject is 60.

**Comment by soonick** [comment]
Thanks for reporting this issue. I am a little busy right now but I will try to fix this as soon as I have some time available.

**Comment by soonick** [comment]
I didn't get any MySQL error message but I added a limit to the field so you can't enter more than 60 characters.
