### ISSUE TITLE
Language setting fail on windows

### ISSUE THREAD

**Issue by toplen** [soonick/poMMo#105]
I Install poMMo on windows 7 , php 5.3.5, apache 2.2
when switch language, it always display english .

**Comment by soonick** [comment]
Hello topolen,

Can you please confirm if you have gettext installed on your system?

**Comment by toplen** [comment]
yes. getext installed. 
and I had installed old pommo from sourceforg, I can change language.

Wu ds

At 2012-12-17 04:35:11,"Adrian Ancona Novelo" notifications@github.com wrote:

Hello topolen,

Can you please confirm if you have gettext installed on your system?

¡ª

**Comment by soonick** [comment]
Hello topolen,

That doesn't sound right. If the older version of poMMo works this one should work too.

I know you need two thins for the translation to work:
  1.- Gettext
  2.- OS language packs for the language you are trying to translate to

But if it works with an older version of poMMo you must have both. What language are you trying to use?

**Comment by soonick** [comment]
Unable to reproduce.
