### ISSUE TITLE
Length of colNames <> colModel or 0!

### ISSUE THREAD

**Issue by toplen** [soonick/poMMo#106]
when run mailings_history.php , alert  Length of colNames <> colModel or 0!  ,   no mailing history item display.
![2012-12-9 0-14-33.png](https://f.cloud.github.com/assets/2995500/1870/c730d4c0-4152-11e2-9aab-828694ddd0d7.png)

**Comment by soonick** [comment]
Thanks for reporting this issue. I will take a look at this.

**Comment by soonick** [comment]
Hello Topolen,

I tried to reproduce this issues, but I didn't see the alert. Can you give me more information of the steps you followed? Do you have mailings in the history? how many?

Thanks,
Adrian

**Comment by soonick** [comment]
Unable to reproduce.

**Comment by nEON7** [comment]
Our poMMo too
- it spit this when opening mailing history, when I comment row in /themes/default/admin/mailings/mailings_history.php

colNames: [
            'ID',
            '<?php echo _('Subject'); ?>',
            '<?php echo _('Group (count)'); ?>',
            '<?php echo _('Sent'); ?>',
            '<?php echo _('Started'); ?>',
            '<?php echo _('Finished'); ?>',
            '<?php echo _('Status'); ?>',
        //  '<?php echo _('Hits'); ?>',
        ],
        colModel: [
            {name: 'id', index: 'id', hidden: true, width: 1},
            {name: 'subject', width: 110},
            {name: 'group', width: 120},
            {name: 'sent', width: 40},
            {name: 'start', width: 130},
            {name: 'end', width: 100},
            {name: 'status', width: 70},
        //  {name: 'hits', width: 70}

error doesn't appear, but no history shows up
maybe situation with old DB not fully uprgraded?
