### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by jtkc** [soonick/poMMo#107]
Hello, 
Loving this fork of pommo, thank you for your work.

I am working on a yahoo hosting server, and it sucks because they prevent the upload of server files, such as .htaccess, .ignoregit, .\* .anything .ihateyahoo ...none of those can be moved to my hosting server.

So, in the pommo root for example, there is an .htaccess file, and i'm hoping there is another way to apply the same techniques used in this file, without using .htaccess / server files....

What do i do when I can't upload .htaccess files to my server??

**Comment by soonick** [comment]
Hello jtkc,

.htaccess file is usually the must unobtrusive way to do what it does. Another way it can be done is by modifying php.ini directly but if they disallow the upload of a .htaccess they probably won't allow you to modify php.ini.

I recommend you sending your hosting support an e-mail, they might be able to help.
