### ISSUE TITLE
ajax/messages.php causes error 500

### ISSUE THREAD

**Issue by r3code** [soonick/poMMo#108]
I just have installed the poMMo from master branch and found an error.
If you click setup_configure.php#ui-tabs-12 which stands for "Messages" tab you don't get the page for the infinite period of time due to server error in ajax/messages.php on line 121.

I have investigated the problem and have found the cause. The error results from missed 
require_once Pommo::$_baseDir.'classes/Pommo_Helper_Messages.php';

It was written only in "if" block so the call to Pommo_Helper_Messages later resuls in PHP Fatal error:  Class 'Pommo_Helper_Messages' not found in /home/d/dreel/maytoday.ru/public_html/mailer/ajax/messages.php on line 121

I rewrote the code and moved the line
require_once Pommo::$_baseDir.'classes/Pommo_Helper_Messages.php';
to begin of file.

Now it works correct.

**Comment by soonick** [comment]
Thanks
