### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#111]
The jQuery version we are using lacks a lot of useful features like delegation. We need to upgrade our version and make sure nothing breaks in the process.

**Comment by kncsvk** [comment]
I tried to add imagemaps function to CKeditor but I failed on (very) old JQ. (https://bitbucket.org/SimplyCast/imagemap-for-ckeditor/wiki/Home).

**Comment by soonick** [comment]
jQuery has been upgraded.
