### ISSUE TITLE
Import issues in pommo 16.1

### ISSUE THREAD

**Issue by ruffcutt** [soonick/poMMo#117]
Hi,

I have just installed pommo version 16.1 and i have import issues.

I have tried two things.

1) Import using csv

2) Import using "list of email addresses"

Both gives me this error.

After this step :

1 non-duplicate subscribers will be imported. 0 were ignored as duplicates.

Notice: Imported subscribers will be flagged to update their records

I clicked "YES"

Error: After clicking yes. It keeps showing "updating" and nothing happens.

Why is it so ?

I have checked with my web hosting company and they told me the server im on now is compatible for this script.

I have tried sending test emails to myself and it works fine.

The only problem now is i cant seems to find a way to add email addresses.

Any help would be awesome.

Thanks

**Comment by soonick** [comment]
Hello Ruffcutt,

Thanks for reporting this issue. Is there any error message on your apache error logs?

Regards,
Adrian

**Comment by ruffcutt** [comment]
I/m new to this so I am not sure what you mean.

**Comment by soonick** [comment]
Are you running poMMo in your computer or in a hosting provider?

**Comment by ruffcutt** [comment]
On my hosting provider. Webfostingpad.com.

Date: Fri, 8 Feb 2013 23:26:46 -0800

**Comment by soonick** [comment]
Ask them where you can find your apache error logs. They will point you to a text file where apache dumps errors. the information on that file may be helpful finding the issue.

**Comment by ruffcutt** [comment]
I will do that right now via chat

Date: Fri, 8 Feb 2013 23:33:04 -0800

**Comment by ruffcutt** [comment]
I got it . What am I looking for?

**Comment by ruffcutt** [comment]
Here is one of the errors I get when trying to import a subscribers.

Deprecated: Function set_magic_quotes_runtime() is deprecated in /home/musclero/public_html/pommo/bootstrap.php on line 56
Complete! Return to Import

**Comment by soonick** [comment]
Have you tried using the newest version of poMMo?

**Comment by ruffcutt** [comment]
This is a fresh download from the site. If thats not the new one . Where can I get it?If you got it can you forward it to me?Thanks

Date: Sat, 9 Feb 2013 19:11:16 -0800

**Comment by soonick** [comment]
Pommo.org is not maintained since 2008 so it has a very old version.

You can get the newest version on github (https://github.com/soonick/poMMo) by clicking the ZIP button. If you have an old database you want to keep you will have to follow the instructions on https://github.com/soonick/poMMo/wiki/Troubleshooting (Unable to login after upgrade)

Regards,
Adrian

**Comment by ruffcutt** [comment]
That worked!!!!! You are the best!!!!

Date: Sat, 9 Feb 2013 23:46:26 -0800

**Comment by soonick** [comment]
Thanks for letting us know.
