### ISSUE TITLE
strict standards messages

### ISSUE THREAD

**Issue by greengator** [soonick/poMMo#118]
Hi Soonick,
I downloaded your version of poMMo (February 6, 2013), loaded onto my server (1and1) and I am testing.  The server is using PHP V5.4 and MySQL V5.0.  Installation went well - successful.  I get warning messages when logging in as admin and when sending a test email.  Examples below (I replaced the actual domain name).

LOGGING IN results in these messages:
Strict Standards: Non-static method Pommo_Helper_Maintenance::perform() should not be called statically in ~~mydomain.com/poMMo-master/index.php on line 90

Strict Standards: Non-static method Pommo_Helper_Maintenance::memorizeBaseURL() should not be called statically in ~~mydomain.com/poMMo-master/classes/Pommo_Helper_Maintenance.php on line 25

Warning: filesize(): stat failed for ~~mydomain.com/poMMo-master/cache/ERROR_LOG in ~~mydomain.com/poMMo-master/classes/Pommo_Helper_Maintenance.php on line 31

Warning: Cannot modify header information - headers already sent by (output started at ~~mydomain.com/poMMo-master/index.php:90) in ~~mydomain.com/poMMo-master/classes/Pommo.php on line 475

SENDING A TEST EMAIL results in these messages:
Strict Standards: Non-static method Pommo_Validate::subscriberData() should not be called statically in ~~mydomain.com/poMMo-master/ajax/ajax.mailingtest.php on line 82

Strict Standards: Non-static method Pommo_Mailing::make() should not be called statically in ~~mydomain.com/poMMo-master/ajax/ajax.mailingtest.php on line 102

Strict Standards: Non-static method Pommo_Mailing::add() should not be called statically in ~~mydomain.com/poMMo-master/ajax/ajax.mailingtest.php on line 108

Strict Standards: Non-static method Pommo_Mailing::validate() should not be called statically in ~~mydomain.com/poMMo-master/classes/Pommo_Mailing.php on line 296

Strict Standards: Non-static method Pommo_Mail_Ctl::queueMake() should not be called statically in ~~mydomain.com/poMMo-master/ajax/ajax.mailingtest.php on line 112

Strict Standards: Non-static method Pommo_Mail_Ctl::spawn() should not be called statically in ~~mydomain.com/poMMo-master/ajax/ajax.mailingtest.php on line 119

Thank you very much for taking this project forward. I really like poMMo better than any of the alternatives and I hope you can help with these warning messages.

**Comment by soonick** [comment]
Hello greengator,

PHP 5.4 Uses strict standards. PoMMo currently is not compliant with it. I am fixing the errors as I find them but in the meantime you can try this:

http://stackoverflow.com/questions/9983286/disabling-strict-standards-in-php-5-4

Regards,
Adrian

**Comment by greengator** [comment]
Hi Adrian,
The .htaccess workaround didn't do the job, it caused many other issues.  After many trial and error attempts, I think I have found what seems to be a simple workaround.  

Find line 28 in bootstrap.php.  It should look like this:
error_reporting(E_ALL ^ E_NOTICE); // [RELEASE]

comment that line and add a line like this:
// error_reporting(E_ALL ^ E_NOTICE); // [RELEASE]
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT ); // [no strict errors]

So far, it is working for me...
greengator

**Comment by soonick** [comment]
That should do the trick. Thanks for sharing.
