### ISSUE TITLE
embed youtube video fail

### ISSUE THREAD

**Issue by iamthed** [soonick/poMMo#119]
hi everybody,

i tried to use embed youtube video in pommo.. when i see the preview (before sending it) it works perfectly.. but when i received the actual email i've seen no video in there (just blank)

can anybody direct me how to embed a youtube video in pommo?
please see this picture below there's a video youtube embeded on it (on preview html message)

![preview html](https://f.cloud.github.com/assets/3005843/175858/ba3780e0-7b5c-11e2-852b-73e85e4c52e8.JPG)

after that i tried to send email
and here's what i've received

![actual receive from email](https://f.cloud.github.com/assets/3005843/175860/edc9422c-7b5c-11e2-9a3c-ce3cd0f81c48.JPG)

please help me to solve this problem..
thx

anyway i use this code 
iframe width="560" height="315" src="http://www.youtube.com/embed/6peOtkIhwdM" frameborder="0" allowfullscreen></iframe

**Comment by soonick** [comment]
Hello,

This is an interesting scenario that I haven't tested. It may be a limitation of the e-mail client, but I leave this ticket in here until I can confirm.

Regards

**Comment by iamthed** [comment]
hey soonick thx for reply..
FYI it's not the limitation of email client since i'm using web gmail.. 
i've tried sending email video via youtube share (email) to my web gmail and it's work perfectly..

i hope somebody could help me with my issue thx

Cheers

**Comment by soonick** [comment]
Hello,

I tried the Youtube share functionality and it seems like it takes a screenshot of the video and adds it to the e-mail, the image is a link to the video on Youtube, but the video is not really there.

Did you see any scenario where you could actually reproduce a video on your email client?

Regards

**Comment by iamthed** [comment]
hey soonic,

sorry for the late reply..
it seems youtube have a two link (one is an image that link to the video on youtube and the other one is an embed video youtube on email)

here take a look at my screenshot 

![screenshot youtube](https://f.cloud.github.com/assets/3005843/190577/64f1564e-7efc-11e2-8d10-47602fa37df4.JPG)

on a no 1 is an image that link to the video on youtube
but no 2 is an embed video youtube on email
(if you click on number 2 it will load video on youtube)

Best Regards

**Comment by soonick** [comment]
Hello,

That is a gmail feature. Whenever you receive an e-mail that contains a link to a youtube video it gives you the option to play it inline.

With this said, you can use pommo to add a link in your mailing pointing to a youtube video and you would get the same result.

Regards,
Adrian
