### ISSUE TITLE
Problem Installing Latest Version

### ISSUE THREAD

**Issue by chrshea** [soonick/poMMo#120]
I am trying to install the latest version but all I get from the install program (install.php) is a blank screen. I am trying to run it under my local test environment (Uniform Server). I have an older version of (Soonick) Pommo installed in the same environment and it works fine. The install isn't complicated and I believe that I did everything that is required. I am using PHP 5.3.8

**Comment by soonick** [comment]
Hello,

Can you check your apache error logs to see if there is any information there?

**Comment by chrshea** [comment]
I have messages:
...PHP Fatal error:  Call to undefined function _() ...\themes\default\inc\configure.header.php on line 12

Line 12 is:
        poMMo.confirmMsg = '<?php echo _('Are you sure?'); ?>';

**Comment by soonick** [comment]
Please check the last entry on: https://github.com/soonick/poMMo/wiki/Troubleshooting.

Feel free to reopen the issue if this doesn't fix the problem.
