### ISSUE TITLE
 update-jquery branch - mailings_start.php jquery ajax tabs not working

### ISSUE THREAD

**Issue by mathiesha** [soonick/poMMo#125]
Hi,

The Branch with the latest jquery update the ajax tabs are missing / not working on the mailings_start.php . Is there a reason behind the disable ? 

Please advice.

**Comment by soonick** [comment]
Hello,

Sorry for the confusion, but that branch is not ready to be used. I'm still working on fixing some incompatibilities issues (Like the one you are reporting). Please use the master branch. Whenever update-jquery branch is ready I will merge it to main.

Regards,
Adrian
