### ISSUE TITLE
Wrong page caching in mail compose

### ISSUE THREAD

**Issue by maximka1812** [soonick/poMMo#127]
I got into strange issue accidently.

Clicked on "Send - Create and send a mailing", looked that prefilled fields use default values. Went to Config and changed them to ones I need (From Name, etc). 

After I went make into composing mail list default values remained. 
Database table changed correctly.

I checked using different browser and saw that all is now correct (my values used). 

I tried to refresh mail composing page, dut it still showed cached version.

As I understand issue is in wrong header or caching settings and browser refresh can't help as this part of page is retrieved using ajax.

You can check other parts that use same approach.

Browser used: IE9

**Comment by soonick** [comment]
Thanks for reporting this issue. I will take a look when I get some time.

Did you try reproducing the issue with any other browser?

**Comment by maximka1812** [comment]
By idea it must be reproduced with any browser. But I tried only IE9

**Comment by soonick** [comment]
Hey @tester13,

Could you please confirm that this happens in other browsers? I don't have access to IE9 to test.
