### ISSUE TITLE
Using Markdown

### ISSUE THREAD

**Issue by maximka1812** [soonick/poMMo#128]
Is it possible to remove HTML Wysiwyg editor and use simple non visual Markdown formatter (with preview via Ajax)?

**Comment by soonick** [comment]
Hello,

What would be the benefit of using markdown instead of WYSIWYG editor?

**Comment by maximka1812** [comment]
Main benefit is ability to make complex mails fast and produce very clean html in result.

As mass mailing software is used regularly by very limited number of people (admin, etc) Markdown is very good solution. 

Last thing that must be mentioned - it is very easy to add and implement.  Do not require much coding.

May be not remove WYSIWYG editor from master, but make branch without it.

https://github.com/michelf/php-markdown/

**Comment by soonick** [comment]
Hello,

Is there something specific that currently can't be done with the WYSIWYG editor? I think that people that use poMMo are not usually people with knowledge of markup and markdown so they rather use something visual.

Regards,
Adrian

**Comment by maximka1812** [comment]
> Is there something specific that currently can't be done with the WYSIWYG editor?

Most things can be done, I think.

I also had been quite big fan of WYSIWYG editors many years ago, until I realised how much time I am loosing and how bad code they produce (code is sometimes also different depending on browser).

> I think that people that use poMMo are not usually people with knowledge of markup and markdown so they rather use something visual.

I doubt it. If you constantly send notices learing very light markup approach that is easy to read is organic.
And Markdown is really simple. 

http://en.wikipedia.org/wiki/Markdown

As I said, best thing is how easy is to add it (contrary to visual editor). 
You already have text box, all you need is to add two lines for markup parsing in PHP and in result you have same html that you can also use to show preview. 

Note that StackOverflow like JS editor for Markdown also exist, but I doubt that we need it.

**Comment by soonick** [comment]
Hello,

I really don't see the need for adding this feature now. The only way I see we could use this feature is to somehow combine the three modes (HTML, WYSIWYG, Markdown) so the user can move between them and use the one they feel more comfortable with.

If you really want this feature you can go ahead and implement it. If you have any question of how poMMo works I'll be happy to help you.

Regards,
Adrian

**Comment by maximka1812** [comment]
> If you really want this feature you can go ahead and implement it. 

Issue is that I am extremely busy guy and not good PHP developer. I can fix bugs usually and find issues, but do not have time to make developing. Especially using git pull requests.

It is very sad that you just closed this suggestion.

You already have  html input box (I mean one without visual editor). 
All that is required is to add checkbox "Accept Markdown formatting" below box and add few code lines.
Markdown lives happily with HTML.

**Comment by maximka1812** [comment]
I specially checked on practice output of visual HTML editor and it is not really good.
