### ISSUE TITLE
Unsubscribe link

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#13]
Unsubscribe link in mailings is sending to non existing page

**Comment by maxnegro** [comment]
Is this still true?

**Comment by soonick** [comment]
I havent checked it. Have you tried to reproduce it?

**Comment by maxnegro** [comment]
I've sent some test messages, but links were createad right, as far as I can tell. I'll have a deeper look and let you know.

**Comment by soonick** [comment]
Perfect,

If you dont find any problem we can go ahead and close the issue.

**Comment by soonick** [comment]
Please check if commit 5081faa953f0de759b7d solves the issue. Reopen the bug if it doesnt.
