### ISSUE TITLE
Advanced Unsubscribe

### ISSUE THREAD

**Issue by maximka1812** [soonick/poMMo#130]
I am making separate entry for advanced unsubscribe functionality.

Let me explain that it is and why it is needed.

For example, you have 20k members (and growing). And you send to groups of them them newsletters from time to time. They are different - some notice for people who did not returned for long, some important  updates of policies, periodic news, requests to change password even. Simple unsubscribe can cause big troubles as it leads to member being unsubscribed from any information.

What I propose:

Same as in simple issue ticket, use

www.youdomain/pommo/unsubscribe?1324234GSGHFGJH35472354DSHKDJHS

But, part after "?" will be different

it'll be encrypted (and base64) text like "subscriber@mail,com;information=0;", key will be generated from salt and admin password

So, it specify email and after ";" allow you to set any user fields to some values. 
In this example, information field will be set to 0 and user will go out of group who recieve informational messages.

I think this proposal is in full compliance with very good groups approach used in POMMO.

**Comment by soonick** [comment]
Hello,

Sorry for taking so long to reply. I don't understand very well how this would work. Can you describe a use case?

Thanks,
Adrian

**Comment by maximka1812** [comment]
Also simple. Code that you see after ? allows to set any user field to any value. 
For example, you have four different email lists where this member is included (each list is defined by group).
Such feature allow him to unsubscribe from each individually. 

For further info just read first ticket post.

**Comment by soonick** [comment]
Hey @tester13,

Sorry about that, I get confused when you start talking about the implementation. Can you please explain the functionality from a user perspective? I will take care of the implementation ;)

Thanks,
Adrian

**Comment by maximka1812** [comment]
> Can you please explain the functionality from a user perspective? I will take care of the implementation ;)

From user perspective it is same unsubscribe link in email 

www.youdomain/pommo/unsubscribe?1324234GSGHFGJH35472354DSHKDJHS 

You click on it, and get simple text ala "Thanks for unsubscribing". 

But you unsubscribe only from certain part of emails. For example it can be exhibition coverage newsletter. 
But important messages will be sent to you still.
