### ISSUE TITLE
Latest version with all updates

### ISSUE THREAD

**Issue by VlatkoN** [soonick/poMMo#131]
Hi Soonick, do you have the latest poMMo version with all updates. I have downloaded 16.1 at http://sourceforge.net/projects/pommo/files/Aardvark/, but the Update Records under unsubscribe and update records personalisation is not working as it should. It does not send the confirmation e mail to the user. 
Any new version? Any comments?
Regards,
Vlatko

**Comment by soonick** [comment]
Hello Vlatko,

I don't completely understand which features you are looking for but you can get the latest version here: https://github.com/soonick/poMMo . Click on the ZIP button on the left top-ish corner of the page.

If this doesn't fix your issue feel free to reopen it.

Regards,
Adrian

**Comment by VlatkoN** [comment]
Thank you - Great Job - Talk to you later.
