### ISSUE TITLE
Manage subscribers add subscribers popup issue

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#133]
While on the manage subscribers page, clicking on "add subscribers" opens a pop up window. 

Issue #1 I have about 14 different subscribers fields that I have added, and the popup has a scroll bar. Now, if I'm adding people manually, I have to scroll down every time to find the right category and to click on the add button. I think making this popup have by default 80% of height and perhaps be adjustable in size would be a good idea.
Issue 
#2 The X button doesn't work to close the window.

Thanks for the hard work by the way!

**Comment by soonick** [comment]
Thanks for reporting these issues. We'll let you know when we get to them.

**Comment by soonick** [comment]
Hello @guisasso,

The X button works for me. Which browser are you using?

Regards,
Adrian

**Comment by soonick** [comment]
Unable to reproduce
