### ISSUE TITLE
Select all subscribers checkbox not working

### ISSUE THREAD

**Issue by Rainmachine** [soonick/poMMo#135]
I noticed today that the select all checkbox is not working on the subscribers_manage page. It throws in this error:

Uncaught Error: Syntax error, unrecognized expression: [@id^=jqg_]. 

Also the paging navigation is not working.

It works in the old 2008 version so i guess it has something to do with the new vs the old jquery code.

**Comment by Rainmachine** [comment]
I managed to find a solution for this issue. The problem is the grid.js file which has old jquery code. 

The selector works if you change the @id^= to id^=   on lines 1033, 1040, 1138 and 1140

This happens mainly because the older versions of jQuery had different syntax.

**Comment by soonick** [comment]
Hello Reinmachine,

Thanks for reporting and finding a fix. Do you want to create a pull request for this fix? If you don't know how to do it I will commit the change later today.

Regards,
Adrian

**Comment by soonick** [comment]
Thanks Rainmachine,

I submitted fixes for both issues. Let me know if you find anything else.

Regards,
Adrian

**Comment by Rainmachine** [comment]
Hi Adrian,
No problemo :D
Cheers for picking up this project, you've done a great job so far! 
regards,Rainmachine

Date: Mon, 13 May 2013 22:13:22 -0700
