### ISSUE TITLE
Change language doesn't work

### ISSUE THREAD

**Issue by dv336699** [soonick/poMMo#137]
When you try to set a language either from the combobox or from config, it just doesn't work.

**Comment by soonick** [comment]
Hello Diego,

Gettext need the locale for the language you want to be intalled on your system. Do you have the locale installed?

**Comment by soonick** [comment]
I am assuming this fixed your problem, if that is not the case feel free to reopen the issue.

**Comment by gregoa** [comment]
I also had this issue, and the reason was the old lib/gettext/gettext.php.
If you search the web for "$MAGIC3" "64-bit" "2500072158", you find plenty of fixed versions to include :)
