### ISSUE TITLE
TSL enable neccessary for Amazon SES but here no option - Please Help

### ISSUE THREAD

**Issue by hsingh01s** [soonick/poMMo#138]
TSL enable neccessary for Amazon SES but here no option - Please Help

Amazon recommends the TSL layer enable.

Connection established. But Test mail sending failure.

**Comment by soonick** [comment]
Hello @hsingh01s,

It will be easier to follow up on your issue if we use a single thread. Can you please try configuring using a gmail account and let me know if it works? I am not positive but I think gmail uses TLS too.

Regards,
Adrian

**Comment by hsingh01s** [comment]
@soonick  Sir,

Gmail is not the requirement. We need Amazon for this. As I have tested with the code in corePHP and it works fine but there is some problem with Pommo The connection established successfully but sending the mail is having some issue.

**Comment by soonick** [comment]
Hello @hsingh01s,

I understand that you want to connect to Amazon. The reason I asked you if it works with gmail is because I know that poMMo works fine with Google which I think uses TLS too. If it works with Gmail in your computer then I will know that is something specific to Amazon.

Can you please give it a try and let me know if it works?

Thanks,
Adrian

**Comment by hsingh01s** [comment]
Sir the package is showing some ajax issue with configurations

**Comment by soonick** [comment]
Hello @hsingh01s,

Can you give me more details so I can fix it?

**Comment by hsingh01s** [comment]
Sir it is some ajax Problem. I can send you the the admin details Sir..

how can I mail you Sir?

**Comment by soonick** [comment]
Can you tell me what you were trying to do when you got the error?

**Comment by hsingh01s** [comment]
On configure ajax is I guess not working
http://obaoja.com/pommo/setup_configure.php

**Comment by soonick** [comment]
Hey, sorry for taking so long to reply.

I didn't understand your answer, what were you trying to do?

**Comment by soonick** [comment]
I need more details to reproduce.
