### ISSUE TITLE
mail processing shows 0% but sends mailings anyways

### ISSUE THREAD

**Issue by filespace** [soonick/poMMo#139]
latest version fresh install

the processing screen never updates while processing a mailing.
shows 0% 0 mails sent but a page refresh after a while will update to 100% and show number of mails sent.. so far max mailign has been 154 emails.

hosted on godaddy.

**Comment by soonick** [comment]
Hey @filespace,

Thanks for reporting this issue. I thing I am seeing the same behavior. I will take a look and let you know if I find a solution.

Regards,
Adrian

**Comment by soonick** [comment]
Hello @filespace,

I think I found the issue. Can you please get the latest code and check if it fixes your problem?

Thanks,
Adrian
