### ISSUE TITLE
poMMo forgot password feature is not working...

### ISSUE THREAD

**Issue by Elyah** [soonick/poMMo#14]
After several tests, I note the forgot password feature is not working both in poMMo Aardvark PR16.1 and this Soonick version. in PR16.1 version the mail is not sent but a pending page appears, and sometimes I get an error message like "PommoHelperMessages::sendMessage() - subject or body empty". In this Soonick version not only the mail is not sent but the reset password link redirects to a 404 error page. I tried to fix the bug but I did not success, as I'm not basically a coder. If anyone can help... Thanks.

**Comment by soonick** [comment]
Hello Elyah,

Thank you for reporting this bug. I will work on this bug and let you know when the problem is solved.

**Comment by soonick** [comment]
Hello Elyah,

I tried to reproduce the bug but I did not find any problem with the forgot password feature. Please try the most up to date master brach.

**Comment by Elyah** [comment]
Hello Soonick,
In that case perhaps it correlates with my server or file permission... I will try the most up to date master brach on another server and let you know the result. Thank you for your assistance.
