### ISSUE TITLE
Bad parameter encoding in URLs

### ISSUE THREAD

**Issue by valerian** [soonick/poMMo#141]
There is an uncommon mail format that i often use : something+anotherthing@somedomain.com

The form validator accepts the "+" character, but the issue is that a lot of URLs are generated the mail as a GET param, and it's almost never urlencoded, so the "+" gets turned into a space : " ".

The fix would be to urlencode() each parameters in generated URLs.

**Comment by soonick** [comment]
Hello @valerian,

Can you tell me in which pages you have noticed this problem?

**Comment by soonick** [comment]
Unable to reproduce
