### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by songsearcher** [soonick/poMMo#150]
Hi Soonick and team,  Is there another release in the works anytime soon?   I downloaded the active code but it would not execute.  

Just curious...  Love the work you have done with this :)

**Comment by soonick** [comment]
Hey @songsearcher,

The master branch should be stable. If you are trying to upgrade from an older version you might want to take a look at: https://github.com/soonick/poMMo/wiki/Troubleshooting#unable-to-log-in-after-upgrade

If you are having a different issue please let us know and we'll try to help you.

Regards,
Adrian
