### ISSUE TITLE
PHP UPGRADE

### ISSUE THREAD

**Issue by Gerhardtf** [soonick/poMMo#152]
pommo worked fine on version 5.3.3 but I have issues when upgrading to php 5.4.4 with current settings below

register_globals : No longer supported by PHP
magic_quotes_gpc   No longer supported by PHP

```
allow_url_fopen        off

ioncube        off

memory_limit    32MB

max_execution_time  30secs

upload_max_filesize / post_max_size     2MB
```

various error messages but on top this appears on the url:

Strict Standards: Declaration of SafeSQL_MySQL::_sql_escape() should be compatible with SafeSQL::_sql_escape() in /usr/www/users/mailetkstm/sharkssupporters/pommo/lib/SafeSQL.class.php on line 242 Strict Standards: Declaration of SafeSQL_ANSI::_sql_escape() should be compatible with SafeSQL::_sql_escape() in /usr/www/users/mailetkstm/sharkssupporters/pommo/lib/SafeSQL.class.php on line 267 Strict Standards: Non-static method Pommo_Helper::parseConfig() should not be called statically in /usr/www/users/mailetkstm/sharkssupporters/pommo/classes/Pommo.php on line 148 Strict Standards: Non-static method Pommo::startSession() should not be called statically in /usr/www/users/mailetkstm/sharkssupporters/pommo/classes/Pommo.php on line 325 Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /usr/www/users/mailetkstm/sharkssupporters/pommo/lib/SafeSQL.class.php:242) in /usr/www/users/mailetkstm/sharkssupporters/pommo/classes/Pommo.php on line 606 Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /usr/www/users/mailetkstm/sharkssupporters/pommo/lib/SafeSQL.class.php:242) in /usr/www/users/mailetkstm/sharkssupporters/pommo/classes/Pommo.php on line 606 Strict Standards: Declaration of Pommo_Template::display() should be compatible with Smarty::display($resource_name, $cache_id = NULL, $compile_id = NULL) in /usr/www/users/mailetkstm/sharkssupporters/pommo/classes/Pommo_Template.php on line 25

**Comment by soonick** [comment]
Can you please try adding this:

```
php_value display_errors 0
php_value error_reporting 30719
```

To your .htaccess file?

**Comment by Gerhardtf** [comment]
thanks for this-it has been done

**Comment by soonick** [comment]
Did it fix the problem?

**Comment by Gerhardtf** [comment]
no, here is the link to see what is displayed : http://mailerza.co.za/sharkssupporters/pommo/

**Comment by Gerhardtf** [comment]
currently set to php 5.4.4...... when set to 5.3.3 it works fine without errors

**Comment by soonick** [comment]
Hello,

Did you make the .htaccess change in your 5.4.4 configuration?

**Comment by Gerhardtf** [comment]
yes it was done

**Comment by Gerhardtf** [comment]
i am leaving the site on 5,4,4 for now in order for you to see the error on http://mailerza.co.za/sharkssupporters/pommo/

pse advise

**Comment by soonick** [comment]
Hello @Gerhardtf,

There is a line in bootstrap.php that starts like this:

```
error_reporting(...
```

Can you change it to this?:

```
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT ); 
```

**Comment by Gerhardtf** [comment]
yip it did the trick -ure da man,,, thank u sir

**Comment by Gerhardtf** [comment]
question is, and this has been asked elsewhere as well, cant seem to find it quickly. how do I upgrade pommo to latest version?

**Comment by soonick** [comment]
You can download the latest and drop it in your server. I recommend you to backup your DB and you will probably need to take a look at this:

https://github.com/soonick/poMMo/wiki/Troubleshooting#unable-to-log-in-after-upgrade

**Comment by misho1** [comment]
Hello,
I am having the same problems, it was working fine on PHP 5.3.3 but now on 5.4.4 I have these ERRORS although I changed to error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT );  in bootstrap.php 
Deprecated: Non-static method PommoHelper::parseConfig() should not be called statically, assuming $this from incompatible context in /home/prez1kolokongo/public_html/news/my_addon/mailing/pommo/inc/classes/pommo.php on line 71

Deprecated: Non-static method PommoHelper::isAjax() should not be called statically, assuming $this from incompatible context in /home/prez1kolokongo/public_html/news/my_addon/mailing/pommo/inc/classes/pommo.php on line 155

Deprecated: Non-static method PommoAPI::getParams() should not be called statically, assuming $this from incompatible context in /home/prez1kolokongo/public_html/news/my_addon/mailing/pommo/inc/classes/pommo.php on line 183

Deprecated: Non-static method PommoAPI::configGetBase() should not be called statically, assuming $this from incompatible context in /home/prez1kolokongo/public_html/news/my_addon/mailing/pommo/inc/classes/pommo.php on line 192

Deprecated: Non-static method PommoAPI::getParams() should not be called statically, assuming $this from incompatible context in /home/prez1kolokongo/public_html/news/my_addon/mailing/pommo/inc/classes/auth.php on line 37

When I add a .htaccess file in the pommo folder with these values:
php_value display_errors 0
php_value error_reporting 30719
I get this ERROR:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@mastakongo.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

Here's my URL: http://www.mastakongo.com/news/my_addon/mailing/pommo/index.php

Thanks

**Comment by soonick** [comment]
Hello Misho,

Sadly I don't have time to support poMMo anymore. Maybe you can find
another PHP developer to help you.

Regards,
Adrian

**Comment by jasimp** [comment]
Hi 

my pommo page looking blank when my server php updated to 5.4
POmmo was working fine with 5.3.3

when i look in to the source of my blank page i can see the below line 


EMS.confirmMsg = '<br />
--
  | <b>Fatal error</b>:  Call to undefined function _() in <b>/home/meducation/public_html/ems/themes/default/inc/admin.header.php</b> on line <b>19</b><br />

could you please advice how i can fix thi issue.

its very sad such a nice application throwing to trash! due to php upgradation.


regards
