### ISSUE TITLE
Unsubscribe email button "Invalid activation code."

### ISSUE THREAD

**Issue by dev-brother** [soonick/poMMo#155]
Unsubscribe element when clicked from within an email generates an  "Invalid activation code." warning when directed to the Unsubscribe page (update.php). 

url directs to:
update.php?email=info@<mymail>&code=a52679f6684775ccd5c1d541df33e0a0

**Comment by soonick** [comment]
Hey @swordsteel. Why did you close the issue? is it not a problem anymore?

**Comment by epiri** [comment]
I am having the same problem, did you manage to solve yours?

When i change permissions in /user/update.php to 655 then it opens a blank webpage ? Is there anything to do with file permissions?

Thanks

**Comment by aadityataparia** [comment]
Same issue. Can anybody help?
