### ISSUE TITLE
Current DYNAMIC ELEMENT List

### ISSUE THREAD

**Issue by dev-brother** [soonick/poMMo#157]
soonick

Do you mind if I add a link to a new page of the WIKI with the current list of Dynamic Elements? If you refer to them by another name let me know.
- [[!unsubscribe]]
- [[!webfile]]

As this list grows it would be great to have a quick reference to them in the WIKI.

**Comment by soonick** [comment]
I don't mind at all. I would appreciate it very much if you did.

**Comment by soonick** [comment]
Hello @swordsteel,

Thanks for adding documentation for dynamic elements and for updating the wiki homepage, they both look really good. I haven't gone through all the documentation in pommo.org but I imagine most of it still applies.

Thanks,
Adrian
