### ISSUE TITLE
Activation email "Invalid activation code." on webpage

### ISSUE THREAD

**Issue by dev-brother** [soonick/poMMo#158]
When confirmation is sent to a new users email address, link looks like so.

http://<my-url-was-here>/confirm.php?code=aef84e8b18a9d8120d12bcbc5bce4dcb

Upon clicking it, the webpage launches and throws out 

-- "Invalid code! Make sure you copied it correctly from the email."

At the top of the page above the body is this...
Strict Standards: Non-static method Pommo_Pending::get() should not be called statically in ./confirm.php on line 47 

Seems to be a repeated issue with the validation code when unsubscribing or confirming.

**Comment by soonick** [comment]
Hello @swordsteel,

Thanks for the issues you reported. I'll take a look at them when I get some time.

Regards,
Adrian

**Comment by soonick** [comment]
Hello @swordsteel,

I wasn't able to reproduce this issue. What version of pommo are you running?

**Comment by Teezone** [comment]
I'm having the same problem - even tried installing a fresh copy of POMMO with a new database..

How is the "code=" generated..?

**Comment by soonick** [comment]
Can you give me steps to reproduce?

**Comment by Teezone** [comment]
Happy to email you a link, if you like.. don't want to post the url in a public forum..

I was asking how the "activation" code is generated in an attempt to reproduce myself - I thought it might have been auto-generated at signup, but I don't see any values in the database. The emails are added manually, using the Admin link, ie. no automatic signup. However, when I did try to subscribe myself, it still didn't work.

Should I see the codes in the database somewhere?

Just to clarify - when I use the default template, the unsubscribe link correctly shows my email address:
user/update.php?email=email@address.com&code=3bc09bd3e3df0db0570dcd64b527c489

But when I click, it takes me to the default Admin page with "invalid activation code"

**Comment by soonick** [comment]
Hey Treezone,

I took a look at the code and it seems like the function Pomm_Subscribers::getActCode(..) is the one that generates the activation code. This is then added to the message (Pommo_Helper_Messages::sendMessage(..) and added to the scratch table (I am not sure why the table is named like this.

Most of this happens at the bottom of activate.php
