### ISSUE TITLE
Moving or Assigning email addresses to and between groups

### ISSUE THREAD

**Issue by dev-brother** [soonick/poMMo#159]
I may have missed this, but is there a way to assign a single or group of emails to a specific group when adding to the system for the first time?

When they are inside a group, how can they be moved to another group?

**Comment by soonick** [comment]
Hello @swordsteel,

Groups are based on filters. For example, you can create a group that matches all subscribers that have an age field and it's value is higher than 18. With this logic you can move members around groups or even have members in more than one group.

You can also use this to import member and add them to a group directly (I think this only works when you on CSV import, but you should be able to convert any plain text file into CSV)
