### ISSUE TITLE
Importing emails

### ISSUE THREAD

**Issue by adrianloaded** [soonick/poMMo#16]
Im trying to import 75,000 emails which keep erroring.

**Comment by adrianloaded** [comment]
Getting this error, with import and copy and paste...

MySQL Query Failed. SELECT DISTINCT email FROM `pommo_subscribers` WHERE email IN

**Comment by maxnegro** [comment]
are you importing from file? single addresses or csv data?

**Comment by soonick** [comment]
Thank you for replying max,

Do you think you can take care of this problem?

**Comment by maxnegro** [comment]
I can try but at the moment I'm unable to reproduce.

**Comment by maxnegro** [comment]
adrian i'm sorry but I'm quite unable to reproduce your issue. are you sure you're using an up-to-date code base? did you have some tables left from a previous installation of pommo? 
please give us some feedback.

**Comment by soonick** [comment]
I'm going to close this bug since max hasn't been able to reproduce it. If you have more information that will help us troubleshoot it you can open it again.

**Comment by maxnegro** [comment]
Just for the record: I was able to import 25k test addresses (generated randomly) before hitting a limit on php execution limit as configured on my test machine (~30 secs). I also tried some "obvious" malformed addresses (empty lines, email containg " and ', and so on). No clue of what may have happened, even if the importing code may enjoy some attention.

**Comment by adrianloaded** [comment]
Hi guys, sorry about late reply, think i was trying to import more than the script could handle.
all loaded in now though

**Comment by maxnegro** [comment]
Tnx for the reply adrianloaded. I think the import should behave better on large loads of addresses, but for the moment I think we should consider closed this issue. Soonick?

**Comment by soonick** [comment]
It sounds like php is timing out. I agree, this issue can be closed.

**Comment by maxnegro** [comment]
php timing out is one of the problems I encountered, but none of them is causing the error reported at the beginning of thread.
