### ISSUE TITLE
Feature Request - Scheduled Sends

### ISSUE THREAD

**Issue by dev-brother** [soonick/poMMo#160]
It would really be great to have a Scheduled Send option for a specific group.

A Scheduled Send would have Group Name, Date and Time.

On the Mailings page the layout could look like:

Send
Scheduled
History

Each Scheduled Send can further be deleted, edited, activated or deactivated.

On top of that, a Scheduled Send could have a pre-send notice sent to the admins email account, say "x" hours/min before sending, and/or have a post-send confirmation sent to the admin email account that the send was successful.

**Comment by soonick** [comment]
This is a clone of #123
