### ISSUE TITLE
Demonstration Mode Issue

### ISSUE THREAD

**Issue by pgqsilver** [soonick/poMMo#163]
After I send the email I am prompted with:

  Mailing Status >> Finished
  Mailing Finished -- Return to Mailings Page
  1 mails sent

Started Mailing #1
13:25:07 > Started Mailing MTA. Spawn #1.
Mail to: msmith@tnt-technologies.com not sent. Demonstration mode is active.
13:25:07 > Mailing Complete.

In the setup, I have Demonstration mode turned off.  Also in mySQL database I have it turned off:

Database: pommo
Table: pommo_config
Field: config_name = demo_mode

In that row, I have config_value, autoload and user_change set to off.

I checked the error_log and it reports:

PHP Notice:  Undefined index: demo_mode in C:\inetpub\wwwroot\pommo\classes\Pommo_Mailer.php on line 82

I was able to change $demonstration = Pommo::$_config['demo_mode']; on line 82 to $demonstration = 'off'; and that seemed to fix the issue.

**Comment by soonick** [comment]
Since you already fixed the issue I'm closing this issue.
