### ISSUE TITLE
Can't edit subscribers

### ISSUE THREAD

**Issue by CarpRAD** [soonick/poMMo#165]
I get the following error message when attempting to edit subscribers:
Fatal error: Cannot use object of type Pommo_Template as array in /home/resjrjln/public_html/keepsakeweddingrugs.com/pommo/themes/default/admin/subscribers/ajax/subscriber_edit.php on line 92 
 In addition, not all of the required editable fields are shown.

**Comment by soonick** [comment]
Hello @CarpRAD,

I wasn't able to reproduce this issue in the latest version of pommo. Which version are you running?

Regards,
Adrian

**Comment by CarpRAD** [comment]
Hi Adrian,
poMMo-2013-04-29
I've installed this version on both my home test server and my online server and I get the same error message.
Rich

**Comment by CarpRAD** [comment]
Sorry, I closed this by mistake.

**Comment by soonick** [comment]
Can you please try the master branch and let me know what happens?

**Comment by CarpRAD** [comment]
I only tried it on my test server but I got the same message.

**Comment by soonick** [comment]
Can you give me the steps to reproduce?

Also, is there any information in your apache error logs?

**Comment by CarpRAD** [comment]
1. Login
2. Click on "Subscribers"
3. Click on "Manage"
4. Click in box to select a subscriber.
5. Click on "Edit checked"
6. "Edit Subscriber" window pops up with limited edit selections and the error message shown above.
   I tried to upload a screen shot but it doesn't seem to work.
   The following are the apache error log entries for today:
   [Wed Aug 07 11:16:24 2013] [warn] pid file H:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
   [Wed Aug 07 11:16:24 2013] [notice] Digest: generating secret for digest authentication ...
   [Wed Aug 07 11:16:24 2013] [notice] Digest: done
   [Wed Aug 07 11:16:27 2013] [notice] Apache/2.2.11 (Win32) DAV/2 mod_ssl/2.2.11 OpenSSL/0.9.8i PHP/5.2.9 configured -- resuming normal operations
   [Wed Aug 07 11:16:27 2013] [notice] Server built: Dec 10 2008 00:10:06
   [Wed Aug 07 11:16:27 2013] [notice] Parent: Created child process 5180
   [Wed Aug 07 11:16:30 2013] [notice] Digest: generating secret for digest authentication ...
   [Wed Aug 07 11:16:30 2013] [notice] Digest: done
   [Wed Aug 07 11:16:32 2013] [notice] Child 5180: Child process is running
   [Wed Aug 07 11:16:32 2013] [notice] Child 5180: Acquired the start mutex.
   [Wed Aug 07 11:16:32 2013] [notice] Child 5180: Starting 250 worker threads.
   [Wed Aug 07 11:16:32 2013] [notice] Child 5180: Starting thread to listen on port 443.
   [Wed Aug 07 11:16:32 2013] [notice] Child 5180: Starting thread to listen on port 80.

**Comment by CarpRAD** [comment]
I may do a complete reinstall.  Since you cannot duplicate this problem, maybe something got corrupted.  I hate to take up your time.

**Comment by CarpRAD** [comment]
I did a complete reinstall including starting the database over again and I go the same error.

**Comment by CarpRAD** [comment]
I've discovered what is causing the problem.  One of my subscriber fields was a date.  When I eliminate that field, the "Edit Subscriber" function works properly.  The date function didn't work the way it did in the original Pommo.  When entering a new subscriber, it didn't provide a date selection popup.

**Comment by soonick** [comment]
Thanks for taking the time to troubleshoot and isolate the problem. I'll try to get some time to look at it next week.

**Comment by soonick** [comment]
Hello @CarpRAD,

I checked an older version of pommo, but I didn't find the date selector functionality.
Was the problem you were getting because the date format you were trying to use was incorrect?

**Comment by CarpRAD** [comment]
Hi sookick,
I agree, the original version did not have the date selector.
When adding my subscriber field for "Wedding Date" I get the following message at the top of the parameter's pop-up:  Wedding Date (Date) - Only calendar values will be accepted for this field. A date selector (calendar popup) will appear next to the field to aid the subscriber in selecting a date.
If I enter an new subscriber the field prompts for YYYY/MM/DD format.  I still get the same error message when I attempt to edit this new subscriber. Also, I don't know if I mentioned this before but when the date field is included add of the field values are blank.
I've tried to attach screen shots but it doesn't work for me.  Would you like me to email you the screen shot directly?

**Comment by soonick** [comment]
Hey @CarpRAD,

Sorry for taking so long to reply.

I am still a little confused about your message, are you actually getting a calendar popup?

**Comment by CarpRAD** [comment]
Hi soonick,
No, I don't get a calendar pop up just the message that one will appear.
