### ISSUE TITLE
My new Pommo

### ISSUE THREAD

**Issue by argyrism** [soonick/poMMo#17]
Hi guys, finally i completed the my pommo version with these new features ( Multiple lists with option to randomize subscribers inside a list, bounce emails management, fckeditor with inline image as attachments, tracking emails control) , the code i created is very messy and it uses external database handling but i tested it and everything works fine, if you are interested i can upload it online, thanks!

**Comment by maxnegro** [comment]
Yes please! I'd like to see your work and I think it would be worth incorporating (maybe after some cleaning up)... :)

**Comment by soonick** [comment]
I'm going to close this one since is not a bug or feature request.

Let us know when you upload your version.
