### ISSUE TITLE
Error when trying to export subscribers

### ISSUE THREAD

**Issue by rguigsaad** [soonick/poMMo#171]
I tested poMMo , and i had problems exporting users , here is the error stack :

Strict Standards: Non-static method Pommo::toggleEscaping() should not be called statically in DIR/htdocs/pommo/ajax/subscriber_export.php on line 29

Strict Standards: Non-static method Pommo_Subscribers::getEmail() should not be called statically in /srv/dataDIR/htdocs/pommo/ajax/subscriber_export.php on line 103

**Comment by soonick** [comment]
Hey @rguigsaad,

What you are seeing is not an error. Those are warnings that are thrown when PHP is ran on strict mode. You can make PHP not show the warnings by adding this to the bootstrap file:

ini_set('display_errors', '0');     # don't show any errors...
error_reporting(E_ALL | E_STRICT);  # ...but do log them

**Comment by rguigsaad** [comment]
Hey @soonick ,
Thank you for your clear answer ^^
I thought all fields were exported but actually only the e-mail addresses are .
