### ISSUE TITLE
How to create the first user ?

### ISSUE THREAD

**Issue by kynoo** [soonick/poMMo#173]
Hello all,

I installed poMMo (fresh install) but am unable to create the admin user as I am immediately prompted to login.
Calling on install.php only tells me poMMo is already installed
What is the workaround ?

Another user reports that after the 7th install it worked for him for some mysterious reason... Well, my karma is not so good it seems.

Thanks for your help

**Comment by rguigsaad** [comment]
You should run the script : https://github.com/soonick/poMMo/blob/master/sql/upgrade.sql
You need to change the prefixe, user , password in the scrip before running it !
Good luck ;)

**Comment by kynoo** [comment]
Thanks for your answer rguigsaad.
It wasn't an upgrade, so I didn't use the fix.
I simply deleted the tables, ran install.php another time and everything went fine.
