### ISSUE TITLE
hello problem with throttle

### ISSUE THREAD

**Issue by shazercunt** [soonick/poMMo#175]
i have the new version the throttle file is php but when i move slider it dosnt register stays at defult

fantastic program thanks

**Comment by soonick** [comment]
Hey @shazercunt,

How did you get the latest version of poMMo?

**Comment by shazercunt** [comment]
i downloaded it from some were the folder name was pommo and this year 12.04 some thing like that can rember were i downloaded it

**Comment by shazercunt** [comment]
the program is brill but the throttle not working has got me into prioblems

**Comment by shazercunt** [comment]
it was released april this year the version i have

**Comment by soonick** [comment]
You can get the latest version from this link:

https://github.com/soonick/poMMo/archive/master.zip

Can you please try it and let me know if it works?
