### ISSUE TITLE
Change name or become maintainer official version

### ISSUE THREAD

**Issue by codingisacopingstrategy** [soonick/poMMo#176]
Hello!

As my friends recommended pommo I gave it a go, only to find out that http://pommo.org/ contains an old version that doesn’t work on PHP5. 

Then I remember they told me about a fork on GitHub, so I managed to find my way here, and this version works great.

My question then is, would it be possible to contact the original poMMo developers, and ask if you can take over maintainership? That way pommo.org can point to this version.

Otherwise I would propose to change the name of this project, so there is no more confusion.

Cheers,

**Comment by soonick** [comment]
Hey Eric,

Thanks for using poMMo, I'm really glad you enjoy it.

We have tried to contact the original developer but he never replied back. I agree that it is confusing to have two versions of poMMo out there but I think changing the name would make it really hard for people to find us and enjoy the improvements we have made.
