### ISSUE TITLE
Error with SMTP concfiguration

### ISSUE THREAD

**Issue by abynur** [soonick/poMMo#177]
hi..as you suggest..here is my problem..1st of all sorry to interrupt here..but i had a problem where cannot sent email through pommo...even sent test email also not successful..after several install/uninstall with many version of pommo..I got this problem..whenever I tried to update smtp this error will happen...
![error](https://f.cloud.github.com/assets/5517695/1197226/bde023ce-24cf-11e3-8633-a98638f874e2.png)

everything will be blank...then i tried to sent test email also will be blank..i've tried each of the email exchanger but still no effect...some said successfully sent but no email been received..please help me..really appreciate your help..tq

**Comment by soonick** [comment]
Hey @abynur,

Thanks for reporting this problem. Can you answer a few questions to help me troubleshoot this issue?
Which version of poMMo are you using?
Which browser are you using?
What are the steps I can follow to reproduce the problem?

**Comment by abynur** [comment]
Hi,

I've test on several version but the latest I used is 'poMMo-aardvarkPR16.1.zip'
For browser, I used IE and Chrome.
The steps:
1st - Configure pommo
2nd - General Tab
3rd - Setup your SMTP server in mail exchanger (neither one of the email exchanger was working)

Please help me..thank you

**Comment by soonick** [comment]
Please try using this version of poMMo and let me know if you still get the same problem:

https://github.com/soonick/poMMo/archive/master.zip

Regards,
Adrian

**Comment by abynur** [comment]
Hi,

I've successfully installed and configured using this version. Managed to set smtp and received test email. But when i tried to send a newsletter I got this error -Unable to spawn background mailer. Is there anything I need to configure other than the in mail exchanger? Thank you.

**Comment by abynur** [comment]
Hi,

I managed to resolved this matter. Thank you so much for your help. Thank you.

**Comment by calacianu** [comment]
Hi guys, I have a problem with pommo, It only sends emails if I pause it and start again. Any ideas why?
Thank you!

**Comment by Milagrow** [comment]
Hello guys, 
I tried this pommo. https://github.com/soonick/poMMo/archive/master.zip
I want to send mail from my localhost through PHP Mail Function option . When I hit at test exchanger it shows success message as "message sent". But I have not received any mail in my inbox and spam both. 
Please help me.
Thanks in advance.
