### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by Razorholt** [soonick/poMMo#178]
Hello!

I edited the config file and double-checked its content. I changed the CHMOD of the cache folder to 777 but when I open any file (index or install) I get a complete blank page. I tried different ports too. 

Any idea?

-Razor

**Comment by soonick** [comment]
Can you check your server error logs and paste some of the related failures?

**Comment by Razorholt** [comment]
[03-Oct-2013 19:19:59 America/Chicago] PHP Fatal error:  Call to undefined function _() in /home/foursea/public_html/pommo/themes/default/inc/admin.header.php on line 19

**Comment by Razorholt** [comment]
I think it's because gettext module is not installed... Where do I go to install it? I have CPanel on my server. 

Thanks!
-Razor

**Comment by soonick** [comment]
Hey @Razorholt,

That's correct, you need to install gettext and php-gettext. How to install it depends on your server or hosting provider. Please contact your server admin or host provider and they will be able to help you.

If you run into any other issue feel free to let us know.

Regards,
Adrian
