### ISSUE TITLE
how to display the total number of pommo subscribers

### ISSUE THREAD

**Issue by lampros** [soonick/poMMo#183]
how can i display the total number of my pommo installation subscribers, 
in user.footer.php or user.header.php ?
thanks

**Comment by soonick** [comment]
Hello @lampros,

Can you give me more details of what you want to achieve?

**Comment by lampros** [comment]
hi! i want to display the total number of active subscribers , in the login.php page ( header or footer ) 
it is the functionality that already exists in pommo  in the admin panel at manage subscriber page
thank you!!

**Comment by soonick** [comment]
Hello @lampros,

I'm sorry but this doesn't seem to give any benefit to our users.
