### ISSUE TITLE
reduce pommo to a class

### ISSUE THREAD

**Issue by micdech** [soonick/poMMo#184]
Hi all,

Pommmo is fantastic, but i think is useful if had a better integration with other main software. 

For example. Wp joomla! Cakephp and other... to integrate it, must be use their users db and their gui...

This maybe incredible....can we think pommo only like a class, without any db, gui and only a class to tell wich table of any existing db to use?

Can we separate pommo core from gui and admin file? Can we think gui like a plugin? 

Let me know
Micdech

**Comment by soonick** [comment]
Hello @micdech,

It is possible to make poMMos throttler work with other databases but it is not something I'm going to be focusing in. Also, making a plugin for each available system out there is not possible so this ticket is not really actionable.

If you want to create a plugin for an specific system I'll be happy to help.
