### ISSUE TITLE
Trouble logging in as Admin

### ISSUE THREAD

**Issue by kevincolyer** [soonick/poMMo#188]
Very pleased you have forked this and are keeping Pommo alive!!! Thanks!

I'm having trouble logging in as Admin since I upgraded from my old pommo to this version. My password seems to be forgotten. I tried the send a new password button but nothing arrives and I get an error message 

Pommo_Helper_Messages::sendMessage() - subject or body empty

Any ideas of what is happening?

Thanks,

Kevin

**Comment by soonick** [comment]
Hello Kevin,

Sorry about this issue. You need to upgrade your DB following these instructions: https://github.com/soonick/poMMo/blob/master/docs/user/troubleshooting.md#unable-to-log-in-after-upgrade

Regards,
Adrian
