### ISSUE TITLE
Problems in compose message screen

### ISSUE THREAD

**Issue by maxnegro** [soonick/poMMo#19]
In the page where you can write or modify the message that is going to be sent, there are two "Continue" submit buttons: one at the top, the other at the bottom of the page. The one at the bottom (along with textual command "Copy text from HTML Message" is not working (i.e.: it goes to the next tab without saving your changes, or fails to copy text from html box). Clicking on Preview tab is not saving your data either.

**Comment by soonick** [comment]
Thank you max, I will check it.

**Comment by MDeguelle** [comment]
This has to do with the fact that on this page, to submit the enetered data javascript actions are assigned to a form id - which must, of course, be unique. Due to there being two forms with the same id, the javascript actions are only assigned to the first one (the top one) and not to the bottom buttons - which makes those submit an empty form. I just delete the top ones to make everything work more smoothly.

**Comment by soonick** [comment]
Hello MDeguelle. Thank you for fixing that problem. Did you make a fork or is there any way I can merge your fix to my repository?

**Comment by MDeguelle** [comment]
I haven't made a fork - Git and I don't seem to play well together. To implement this fix, just open the file /themes/default/admin/mailings/mailing/compose.tpl and remove line 6 to 22 (the entire form with id "compose"). 

The top buttons will then disappear on the compose page; but the bottom ones will work just fine which provides a, in my opinion, more logical workflow anyways with the buttons beneath the form fields.

**Comment by maxnegro** [comment]
There was another approach proposed by armitage, see commit here: https://github.com/armitage/poMMo/commit/5d452a24126d10e450519307c8841ccd727c0b03

**Comment by soonick** [comment]
Thank you both.

Right now I am a little bussy. But as soon as I finish the things I am working on I will apply on fix or the other.

**Comment by soonick** [comment]
Agregue fix de armitage. Closed by f53975cae3662ecc911b903654b34a3d54a854ff
