### ISSUE TITLE
error sending email test

### ISSUE THREAD

**Issue by mokiwaa** [soonick/poMMo#197]
I always receive from pommo error sending email, when i try test configuration!
Can somebody help to find out is the problem?

**Comment by jasimp** [comment]
you have to configure your mail server properly

**Comment by mokiwaa** [comment]
Yes, I have tried all possible configuration, but still give me the error. I ask to my hostserver to check my configuration, and in all of them, he report the same error, just like happens to me!

**Comment by jasimp** [comment]
get me both your mail server details as well as your configuration details.
which mail function you used?
there are 3 options are available
you have to choose the proper one which is matching to your server.
you can test this through the test link
if the first two not working, then you have to configure the smtp relay using your server details

always keep the authentication off mode (SSL OFF) so choose the port acordingly

then try

**Comment by mokiwaa** [comment]
Tank you Jasimp for your help, after a few hours messing with configuration, pommo is working now, I dont what happens but is working, thank you one more time, for your reply.
