### ISSUE TITLE
Add Attachments

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#2]
Option to add attachments to mailings

**Comment by Scarlette** [comment]
Hi there,

You may like to try FCKeditor Ajax manager created by phpletter.com  - http://www.phpletter.com/Demo/FCKeditor-Ajax-File-Manager/ 

I have used this for my Pommo install and am able to add attachments to mailings through the link button in fckeditor enabling you to upload files to the server and also place images directly into the emails.

I hope this is useful to someone else.

**Comment by soonick** [comment]
Thank you for your suggestion. I will check that out.

**Comment by soonick** [comment]
Attachments functionality merged to master, ready for testing

**Comment by argyrism** [comment]
i tried the code you have posted for attachments functionality and in firefox it can attach the files (and only upload files + write data to attachment_files in database) , somewhere there is a bug and it cannot add the data to the mailings_attachments. Also it does not upload anything if using IE. Dont have much time to find the problem, is your attachments implementation full? i only see an attach button under compose, nothing more.... thanks for the hard work keep it going.... i managed to add lists to pommo and bounce tracking, but my code is a mess and i need time to make it look better

**Comment by soonick** [comment]
Hello argyrism,

That button was all I did. I didnt make the implementation very fancy.

I did test that firefox sent the attachments, but I will test it again since it didnt work for you. I didnt test in IE, thank you for doing that for me, I will try to find what is happening there.

I will be looking forward to seeing the new features in your version.

Thank you.

**Comment by soonick** [comment]
Hello argyrism,

I fixed the attachments upload for IE and Opera.
I tested it on IE7, Opera, Firefox and Chrome.

If you keep having issues let me know so we can troubleshoot it.
