### ISSUE TITLE
Can't stop sending process

### ISSUE THREAD

**Issue by themaniac** [soonick/poMMo#206]
Hi, 

i've started a sending process (7 email with single attachment) but pommo didn't send a mail.

the problem is that now is trying to send mail for about a day and i cannot stop the process.

what can i do?

**Comment by donPabloNow** [comment]
Welcome  soonick/poMMo! 


You are invited to access Obey.'s Customer Self Service Portal 


 By accessing this portal, you can track your requests online,

access knowledge base and join the community forums.
ACCEPT THE INVITATION



 




Your user name is reply@reply.github.com | You can also click here to accept the invitation 





 



Thank you, Obey. Administrator






 








This email has been sent to you&#x28;reply&#x2b;abrlhwys3xavvqa6oxqw5lf42ghf7evbnhhaeqzolm&#x40;reply.github.com&#x29; by don&#x40;obeyi.com from Obey.. Please contact the sender&#x28;don&#x40;obeyi.com&#x29; for any clarifications.
