### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by aleray** [soonick/poMMo#212]
Hi,

I've been trying to install pommo on a server using https/ssl. It seems like it causes a jam when I try to send a test mailing list (haven't try to send a real mailing). The mail isn't shipped and the mailing part of Pommo get stuck.

I was wondering if there was anything to know about ssl configuration. For now, I've been deactivating ssl, but would really like to put it back.

Thanks

**Comment by soonick** [comment]
Hello @aleray,

I don't know of any issues when running pommo using https. If you want to look into this issues I'll be happy to help you.

Regards,
Adrian

**Comment by aleray** [comment]
Hi soonick, and thanks for your reply.

i was brief because I was wondering if there was anything obvious that I missed. I will try to elaborate a little bit more.

I'm new to SSL. I'm using nginx on port 80 and proxy every dynamic code to apache on port 8080. Only nginx is secured by SSL. 

Here is my nginx conf: http://pastebin.com/mGauPYFH
Here is my apache conf: http://pastebin.com/p4uHtCEY

on the Apache conf, the Alias directive points to the pommo install.

I haven't been further than trying to send a test mail, but basically using this config, if:
1. I go visit the mailings_start.php page, fill in the wizard and choose "send test";
2. send a test mail (interface claims it worked);
3. go visit mailings_start.php page

I get a message "A Mailing is currently processing. Visit the Status page to check its progress."

If I visit the "mailing_status.php" page, I read "Mailing Status » Stopped". Neither "resume mailing" or "stop mailing" seems to have effect. The mailing is "jammed" and I can't find a way to unlock it.

I don't have this kind of troubles when I'm not using SSL; What could cause it?

Thanks a lot

Alex

**Comment by altshiftzero** [comment]
I think the first thing you should check is if the files included in the output (javascript and ajax-requests) are using ssl. By default if a script is included with a http:// within the source and you are using the site with https:// the script will be blocked by the browser. you should check and remove the http: that only the // will remain in the beginning of the scriptlink That way the HTTP/HTTPS will be automaticaly chosen depending on the request.

**Comment by ser** [comment]
I suspected the issue is that backend server uses the http, and frontend is https.

And yes, it's the reason. A very dirty patch for it, which makes the server working, is to edit `Pommo_Mail_Ctl.php` and replace:

`$socket = fsockopen($ssl.Pommo::$_hostname, Pommo::$_hostport, $errno, $errstr, 25);`

with:

`$socket = fsockopen("localhost", Pommo::$_hostport, $errno, $errstr, 25);`

Voila!

**Comment by aleray** [comment]
Hi, I realised I never closed this issue, but it made the deal. Thanks for your help!
