### ISSUE TITLE
Blank Screen after install

### ISSUE THREAD

**Issue by marc666** [soonick/poMMo#213]
After I installed pommo step by step I receive blank screen if I open http://ip-adress/pommo/ or http://ip-adress/pommo/install.php
If I change the language in config.php, then I receive at the "http://ip-adress/pommo/install.php" "pommo is already installed" 
If I follow the link "continue to login page" I receive "php gettext module is not installed"
If I install it: Blank site again.....

I would really appreciate help on this issue.

**Comment by marc666** [comment]
To clarify: I don´t need to change the language, I´m fine with "en". But if I choose en as language -> blank screen

**Comment by soonick** [comment]
You only get a blank screen when you choose "en" as language?

Do you have the gettext module installed? PoMMo depends on it.

**Comment by marc666** [comment]
Do I need gettext also for "en"? 
If language is en I get blank screen, 
If I change the language in config.php, then I receive at the "http://ip-adress/pommo/install.php" "pommo is already installed"
If I follow the link "continue to login page" I receive "php gettext module is not installed"

**Comment by soonick** [comment]
Yes, gettext is a project dependency. Gettext functions get called in the code for ask languages.

**Comment by marc666** [comment]
But gettext is per definition only for NON english; So is it neede for POMMO also for the english version anyway?

**Comment by soonick** [comment]
Gettext is not per definition only for non English. Gettext gets a key and tries to find the value in different maps depending on the language. It happens for pommo that the default language is English and the keys we are using are literal text, but this is not necessary. Gettext also shows different text depending on singular or plural regardless of the language.
