### ISSUE TITLE
Handle multiple usernames/accounts

### ISSUE THREAD

**Issue by bobnvic** [soonick/poMMo#24]
I set up websites with poMMo for clients and I often have to get into the site for them to adjust something or send their mailing if they aren't available.  Since they can set the password to whatever they want I've been going into the database to temporarily change the password so I can log in, then changing it back (it's a hash so I have no idea what their actual password is).  This is a pain, but I didn't see a relatively simple way in the code to add another account (in the original poMMo code, I haven't looked through your fork that closely).  

Is there a better way of doing this that I've missed, or would you consider adding this functionality?

Thanks,
bobnvic

**Comment by soonick** [comment]
We will think about adding the functionality. Will let you know in this thread.

**Comment by soonick** [comment]
I am going to start working with this.

**Comment by bobnvic** [comment]
Thanks!  Will you update this thread when it is ready for initial testing?

**Comment by soonick** [comment]
Yes, I will update this thread when I am done.

**Comment by soonick** [comment]
Hello. It seems I have finished making a solution that will allow to have multiple poMMo users. I am sure it is not a very elegant solution but I think it solves the problems this issue pointed.

I will appreciate any feedback.

**Comment by bobnvic** [comment]
Thank you for the implementation of my request. This as well as the other changes you have made are much appreciated.

I am having issues with adding users.  It usually has the "Add User" button grayed out and won't activate, however it has worked a couple times.  Any idea why this might be an issue?

Thanks,
Bob

**Comment by soonick** [comment]
User name and password length must be 5 characters or more and the two password fields must match for the button to activate.

**Comment by bobnvic** [comment]
Thank you!  That was certainly a fast response.  I was trying user names like 'test' and that was the problem.  Works great! Thanks again.
