### ISSUE TITLE
Language setting not honored

### ISSUE THREAD

**Issue by armitage** [soonick/poMMo#25]
I can't set the language to anything different then en, neither config file change nor per Session change in the admin have any Effect. (I even overwrote the en Fallback in Pommo.php). Any Clue to what's the Problem?

best regards
armitage

**Comment by soonick** [comment]
Thank you for reporting the problem. I will check what is happening.

**Comment by maxnegro** [comment]
have you seen any errors in cache/ERROR_LOG?

**Comment by armitage** [comment]
Hy maxnegro, no i have no errors at all in my log, it looks like the whole
Pommo_Helper_L10n::init
is not really called (or doesn't do its stuff)

Can you two switch languages on your edge installations right now?

**Comment by soonick** [comment]
I can't switch languages either.

Max, you have been working on translations. Can you?

**Comment by maxnegro** [comment]
Yep, actually I can. And can't remember having had any problem using this feature at all (the whole point of my work on it l10n was actually due to the fact that setting the italian language worked but showed very poor and inaccurate translations...)

**Comment by maxnegro** [comment]
Are you using "native" gettext support (ie php gettext extension) or are you relying in software emulation (as provided in lib/gettext/gettext.inc gettext.php)?

**Comment by armitage** [comment]
Max,
I'm using native gettext support with PHP 5.3

**Comment by maxnegro** [comment]
Uhm. Same here. Can you try with my tree? I doubt there will be any difference, but at least we can exclude differences in installed base.

**Comment by soonick** [comment]
I am also using native gettext and nothing. I will have to check what is happening.

**Comment by armitage** [comment]
Max, 
I tried with yout tree too now, but with the same (none) result.

**Comment by maxnegro** [comment]
Very strange. It seems we all have same setup (php 5.3 and native gettext). Maybe something in php.ini? php safe mode maybe? I'm quite lost here.

**Comment by armitage** [comment]
Solved!

Ok Guys I solved the issue with the languaging support by digging into the php gettext documentation. You need to have the language to switch to being listet when you issue the command: locale -a
So for example on ubuntu and german you need to install the package "language-pack-de" after you've done that gettext will be able to find the correct translations in pommo. Perhaps we should document that fact somwehre in the README

**Comment by maxnegro** [comment]
nice catch! strange thing is I'm able to switch also to languages not listed in locale -a. maybe the requirement is only for the "main" language (the one indicated in config.inc)?

**Comment by armitage** [comment]
Max,
no i don't think so (as i interpret the php-gettext docs) at least for ubuntu/debian this should be true, what linux distribution are you using?

**Comment by maxnegro** [comment]
soonik, if you're on debian/ubuntu can you please verify you have the package "locales" installed?

**Comment by maxnegro** [comment]
armitage: ubuntu maverick. locale -a reports C
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US
en_US.iso88591
en_US.utf8
en_ZA.utf8
en_ZW.utf8
it_CH.utf8
it_IT
it_IT@euro
it_IT.iso88591
it_IT.iso885915@euro
it_IT.utf8
it_IT.utf8@euro
POSIX

and i'm also using localepurge, so I should have no traces of other locales on my system.

**Comment by armitage** [comment]
Max, and you are able to switch to french too, for example?

**Comment by maxnegro** [comment]
Yes I've tried a few, including portoguese and russian :)

**Comment by armitage** [comment]
Hmm, very strange.
I'm on lucid and the behaviour is like described on http://www.php.net/manual/en/book.gettext.php so after installing the de language pack i can switch between german an english and nothing else.

**Comment by soonick** [comment]
Great job armitage and maxnegro.

I am running ubuntu 10,10 and as armitage I can only use the languages for wich I have the language pack intalled.

**Comment by maxnegro** [comment]
ok great. my machine has been blessed and I didn't know. should I run for world domination?

**Comment by armitage** [comment]
Hehe,
always a worthy goal to keep in mind Max.

I think we can finally settle that Issue now, since the info has been added to the README now and all of us can switch languages. Thank's a lot guys.
