### ISSUE TITLE
Can't create smtp relay.

### ISSUE THREAD

**Issue by onoff** [soonick/poMMo#29]
I can't create smtp relay.
Get the error message:

Fatal error: Uncaught exception 'phpmailerException' with message 'SMTP Error: Could not connect to SMTP host.' in /home/mysite/public_html/poMMo-093c573/lib/phpmailer/class.phpmailer.php:820 Stack trace: #0 /home/mysite/public_html/poMMo-093c573/ajax/ajax.smtp.php(119): PHPMailer->SmtpConnect() #1 {main} thrown in /home/mysite/public_html/poMMo-093c573/lib/phpmailer/class.phpmailer.php on line 820

Any Idea?

**Comment by soonick** [comment]
Hello onoff,

It is saying that it is not able to connect to the smtp server. Do you have an smtp on the computer in which you are testing poMMo?

What were you trying to do when you got the error?

**Comment by jaraddowning** [comment]
I can reproduce the error on a clean install of poMMo. The error message appears in the pop-up window where you used to be able to enter your relay information. I tried hard coding the smtp server information (lib/phpmailer/class.phpmailer.php) and was able to send test messages but when sending out a distribution the proc froze after the first spawn. I managed to find an old copy of the software from one of my older servers and it doesn't throw the error.
Server info: ubuntu 10.10 & PHP 5.3.3-1

**Comment by soonick** [comment]
Can you give me more information?

What version of pommo is giving you the error?
How can i open the pop-up window to get the error?

**Comment by jaraddowning** [comment]
The most up to date version of poMMo as of 1/31/2011.

What I did to reproduce the error:
0.5. Install fresh copy of Ubuntu 10.10 - run updates/upgrades & install LAMP via tasksel then rerun updates/upgrades
1. git clone to web root (/var/www) then change owner/group to www-data
2. Create database (using phpmyadmin 3.3.7deb3build0.10.10.1) for poMMo
2. Install poMMo by visiting the URL http://localhost/poMMo
3. Provide appropriate information for the database, admin email, website, etc.
4. Once installed - Go to admin > setup > configure then select the General tab
6. Select SMTP Relay as the mail exchanger
7. Click on Setup your SMTP Servers
8. Pop-up with error message:

Fatal error: Uncaught exception 'phpmailerException' with message 'SMTP Error: Could not connect to SMTP host.' in /var/www/poMMo/lib/phpmailer/class.phpmailer.php:820 Stack trace: #0 /var/www/poMMo/ajax/ajax.smtp.php(119): PHPMailer->SmtpConnect() #1 {main} thrown in /var/www/poMMo/lib/phpmailer/class.phpmailer.php on line 820

The SMTP server is not on this machine but is located inside the local network. Its an exchange 2003 server but it is configured to allow all types of SMTP connections, I've never had any problems before (well none for SMTP connections). But this is moot as I haven't entered any information about the server into poMMo yet. As I said earlier, if I go into lib/phpmailer/class.phpmailer.php and put in my server info I can send the test emails successfully.

Please let me know if you need any further information.

**Comment by soonick** [comment]
Thank you for the information. It will be very helpful to find the issue.

**Comment by haccp** [comment]
Hallo,
I have too problem with SMTP pop-up setting window. In my case I don't see nothing.

**Comment by jamesarbrown** [comment]
PHP is not my thing, infact this is first time I have looked into a PHP prog, but I think the underlying cause is in ajax.smtp.php

This bit of code creates a "empty" smtp server

if (empty ($smtp[1]))
    $smtp[1] = array (
        'host' => 'mail.localhost',
        'port' => '25',
        'auth' => 'off',
        'user' => '',
        'pass' => ''
    );

But this code goes on, to test it immediately on initiation

// Test the servers
$addServer = FALSE;
$smtpStatus = array ();
for ($i = 1; $i < 5; $i++) {

```
if (empty ($smtp[$i])) {
    if (!$addServer)
        $addServer = $i;
    continue;
}

$test[$i] = new PHPMailer();
```

etc

So if there is no mail.localhost or access to port 25 (ie selinux or iptables etc) then it bugs out immediately.

It needs to open the window with empty textboxes if SMTP_1 is empty in database and let user amend before having a "test" button.

James

**Comment by soonick** [comment]
Hello James,

Thanks for looking into this problems. I have been very busy recently but I will take a look into your sugestion soon to see if it fixes the problem.

Regards.

**Comment by jamesarbrown** [comment]
Its this bit here

```
if (@ $test[$i]->SmtpConnect()) {
    $smtpStatus[$i] = TRUE;
    $test[$i]->SmtpClose();
} else {
    $smtpStatus[$i] = FALSE;
}
```

I think it is supposed to attempt to connect and set smtpstatus as true of false., but instead its causing an exception. The smtpConnect is causing the exception. Again dont know PHP well enough, but needs like Java a try/catch.

Will look into it as I need to get my mailserver back up!

If I come up with anything will post it here.

James

**Comment by jamesarbrown** [comment]
Hi Soonick,

After thinking and looking it soon came clear that class.phpmailer.php was causing the exception, ie an external class to Pommo.

In there it says
  /**
- Initiates a connection to an SMTP server.
- Returns false if the operation failed.
- @uses SMTP
- @access public
- @return bool
  */
  public function SmtpConnect() { 
  blah blah...

"Returns false if the operation failed." But clearly it does not, it can also cause an exception driven by the following code lower down.

```
    if (!$connection) {
      throw new phpmailerException($this->Lang('connect_host'));
    }
```

So in my view the only way to fix pommo is to catch the exception in Pommo as follows
ajax.smtp.php

```
try {
    if (@ $test[$i]->SmtpConnect()) {
        $smtpStatus[$i] = TRUE;
        $test[$i]->SmtpClose();
    } else {
        $smtpStatus[$i] = FALSE;
    }
} catch (phpmailerException $e) {
    $smtpStatus[$i] = FALSE;
}
```

Have tried and it worked... said could not connect, lets me change details and then "update relay 1" changed from nice stop sign to tick.

Happy Days.

James

**Comment by soonick** [comment]
Hello James,

It seems like you have fixed this bug. Why don't you fork me and commit the fix to your repository so I can then merge to mine?
If you are not familiar with git or github I can help you with the process.

Let me know what do you think.

Adrian

**Comment by jamesarbrown** [comment]
I am a bit new to git, but have been using gitosis lately, so will fork and push back the changes... once done will let you know

**Comment by jamesarbrown** [comment]
Done....I hope!! 

https://github.com/jamesarbrown/poMMo

**Comment by soonick** [comment]
Thanks for the fix James.

If someone still has this problem please reopen this issue.

**Comment by jaraddowning** [comment]
I wanted to report in and let you know this is now working flawlessly for me. Thank you - soonick and the new godfather of soul Mr. James AR Brown.

**Comment by jamesarbrown** [comment]
just the name, white man, can't sing, terrible guitar skill  :)

**Comment by hsingh01s** [comment]
Hello @soonick Please help me out for the Transport Layer Security (TLS) enabled. as my external server is recommending it to be enabled.
