### ISSUE TITLE
Add a Open/read tracking system

### ISSUE THREAD

**Issue by pixeline** [soonick/poMMo#3]
It's fairly easy to implement.
From the admin side, it can just be an option (checkbox) in the Message Sending process: "Do you want to track the read ratio of this mailing?"
If ticked, an img tag pointing to a php file with the user id and the mailing id has to be appended to the message body code.
The serverside script uses the get variables to update the mailing and user read counter, then outputs an 1px transparent gif.

**Comment by soonick** [comment]
Thank you for your suggestion. It seems like a very good feature.
I'll keep it in here and implement it when I have time, or if you want you can do it and I will add your commit.

**Comment by llynix** [comment]
Just to maybe give someone a heads up.. or maybe they can duct tape this into something.  Here's my simple tracker:

First this rule in .htaccess
RewriteRule ^(track-[0-9]{8}).png$ /email/tracker.php?id=$1 [L]

Then this is tracker.php
<?php
header('Content-type: image/png');
echo gzinflate(base64_decode('6wzwc+flkuJiYGDg9fRwCQLSjCDMwQQkJ5QH3wNSbCVBfsEMYJC3jH0ikOLxdHEMqZiTnJCQAOSxMDB+E7cIBcl7uvq5rHNKaAIA'));

$server = '';

$user = '';

$pass = '';

$db_name = '';

$time = time();

$mysqli = new mysqli($server,$user,$pass,$db_name);

$query = $mysqli->prepare("INSERT INTO `emailhits` ( `id` , `ip` , `page`, `timestamp`, `useragent` ) VALUES ( ? , ? , ? , ? , ?);");

$query->bind_param("sssis",$_GET['id'],$_SERVER['REMOTE_ADDR'],@$_SERVER['HTTP_REFERER'],$time,$_SERVER['HTTP_USER_AGENT']);

$query->execute();

?>

This creates 1px png image and stores all information in a database.  Of course the database will have to be created.

Then theres track.php
<?php
$server = '';

$user = '';

$pass = '';

$db_name = '';

$mysqli = new mysqli($server,$user,$pass,$db_name);

$query = "SELECT `id` FROM `emailhits` GROUP BY `id` ORDER BY `id` DESC;";

$result = $mysqli->query($query);

while($row = mysqli_fetch_array($result, MYSQLI_NUM)) {

  echo $row[0] . ' <a href="' . substr($row[0],-8) . '">Email</a>';

  $q2 = "SELECT COUNT(`ip`) FROM `emailhits` WHERE `ip` != '65.115.220.163' GROUP BY `id` HAVING `id` = '$row[0]';";

  $r2 = $mysqli->query($q2);

  $row2 = mysqli_fetch_array($r2, MYSQLI_NUM);

  echo "<br />&nbsp;&nbsp;Visits $row2[0]<br />";

  $q3 = "SELECT COUNT( DISTINCT `ip` ) FROM `emailhits` WHERE `id` = '$row[0]' AND `ip` != '65.115.220.163';";

  $r3 = $mysqli->query($q3);

  $row3 = mysqli_fetch_array($r3, MYSQL_NUM);

  echo "&nbsp;&nbsp;Uniques $row3[0]<br />";
}
?>

Which crudely shows the results.

Github formatted it all funny.. tried to fix it.. I hope it's readable.

**Comment by argyrism** [comment]
I think i can help creating this feature. Also i would suggest to change the database and put another field at the table handling the subscribers, sorry for my english, im not a native speaker, my native language is Greek. By adding an extra field at this table, we use it as a list id or even group id or something else and we can make pommo to have multiple lists , modify duplicates check to list check not table check, so we can have the same emails into other lists, also we can add a separate table for bounces and have there only the subscriberID and number of bounces. All these can be easily implemented if we find a way to add links or do the trick with the 1pixel icon for every link we add. If we can make it and add links to the email body then i believe it will be very easy to do the rest, i need some guidance from you at the beginning to get quickly some valuable information about how the current script works. Thank you guys keep the good work.!!

**Comment by argyrism** [comment]
forgot to tell the obvious : after number of bounces reaches a limit on that table we just disable that email, also using multiple lists pommo will be able to handle much more emails (just oprimize sql by list id) and also every email will be inserted with unique id inside table even  if it is a duplicate (in table - different  list id) - using it this way we can make the tracking easier (even if subscriber fields are applied)

**Comment by argyrism** [comment]
the links we put in the email must have a way to get somedata automatically like putting file.php?parameter=[domething generated automatically from pommo - like subscr.id]

**Comment by soonick** [comment]
Hello argyrism,

Thank you for offering to help. If you need guidance getting familiar with the code I think I can help you with that. Just please be patient if it takes me some time to reply because sometimes I am a little busy.

Modifying the database might be a good idea, but I think we will have to plan it well, because the way pommo communicates with the database is a little obscure, It uses some database libraries I am still not completely familiar yet.

But feel free to ask me anything and I will try to answer as fast as I can.

Welcome.

**Comment by soonick** [comment]
I'm going to start working on this feature.

**Comment by argyrism** [comment]
i have implemented this and it works fine, the code you have provided before is doing the job right, i do not have time to upload the whole project online but i will provide code for this as well as for embeded images (inline images) -> you only have to replace a folder with the one i will send, so using this there is no need to implement the attachments module you started except if you need attachments other than images

**Comment by argyrism** [comment]
for the inline image attachments just download this zip file and overwrite your wysiwyg folder with this (under themes folder) 
http://www.format-cy.com/wysiwyg.zip . This is a modified fckeditor with inline image attachments for pommo. It works fine but the only thing left to change is to modify the regular expression so that it gets right the width , height and other properties of images, now you can only press the image buttton within fckeditor - upload to server- then select the image and it is shown within fckeditror, the regular expression is modified to make these images as part of email body. Enjoy!

**Comment by argyrism** [comment]
sorry for the delay, i was in the middle of something and i now finished. Also replace your php mailer with this one. http://www.format-cy.com/class.phpmailer.php . This is were the reqular expression is.

**Comment by soonick** [comment]
Thank you argyrism,

I will check your wysiwg version when I start working on Issue # 1 because I think it is more relevant to that one. I wasnt able to access your phpmailer file, maybe if you put it in compressed file so your server wont parse it.

Thank your for your help.

**Comment by argyrism** [comment]
yeap, my mistake! i did not realize that, download it from here http://www.format-cy.com/class.phpmailer.zip

**Comment by soonick** [comment]
Now you can see how many hits your mailing has had in the mailings_history page.
