### ISSUE TITLE
How to upgrade from old version

### ISSUE THREAD

**Issue by raj2ras** [soonick/poMMo#30]
Is it possible to easily upgrade a old version of PoMMo to the new one without losing any data or having to re-configure it all over?

**Comment by soonick** [comment]
You shouldn't need to configure it all over again. I think that if you make a backup of your db. Make a clean install of the new version and then apply the backup to the new database it should work.

I am not 100% sure, so keep your old version and old db in case the new one does not work.

Let me know how it went.
