### ISSUE TITLE
Divs all messed up

### ISSUE THREAD

**Issue by bachu** [soonick/poMMo#34]
Soonick, 

Before all, thanks for working on pommo again.
It´s a great tool.

I´m having a problem I used to have with the old pommo. 
I try to send some newsletters and they appear all messed up.

The height of divs is not the right one. I have some vertical divs floating at both sides with background, repeated images, and non of them show.

I try to send them with phplist or newsletter x and they all work fine, except the vertical floating divs.

Do you know anything about this?
Is it something I do wrong while designing the newsletters?

Thanks again!

**Comment by soonick** [comment]
Hello bachu,

If you are only having this problem with pommo,  it is unlikely that you are doing something wrong.

I will need the layout you are using in order to reproduce the problem and troubleshoot it.

Regards,
Adrian Ancona

**Comment by bachu** [comment]
Soonick, 

I sent you an email with 2 newsletter attached.

Thanks!
Bachu

**Comment by bachu** [comment]
Soonick, 

I was trying Newsletter X Demo, with the same newsletters and the html are read perfectly.
I don´t know if this might be useful to you.
http://www.phpnewsletter.org/

Thanks!
Bachu

**Comment by soonick** [comment]
Hello bachu,

Please upload the code for the newsletters to your server so they are accessible not only by me.
Also please explain the procedure you followed to for sending the mailing. What character you chose in the set up tab, What and where did you put in the compose tab.

Thanks,
Adrian Ancona

**Comment by soonick** [comment]
Hello bachu,

The textarea on the top of pommo's compose window is a WYSIWYG editor, did you put your code in there?
That editor doesn't exepct HTML. Please reopen if I misunderstood what you did.

Regards

**Comment by bachu** [comment]
In the Compose window, where ir says HTML Message, I pasted my html script.

How do i have to do to do it correctly? I use Dreamweaver to edit my htmls.

Thanks!

**Comment by bachu** [comment]
I figured it out... was not difficult lol.
From my html in dreamweaver, design window, copy
on the pommo composer paste.
¡Everything working excellent!

Thanks Soonick

**Comment by bachu** [comment]
I have one more question/trouble.

I use linked images that I uploaded on a server.
When I paste the mail into the WYSIWYG editor I see them correctly, but when I receive the mail I don´t see the images.
How do I have to do?

Thanks again!

**Comment by soonick** [comment]
Hello bachu,

It seems like the editor poMMo currently uses doesn't allow you to add raw HTML, which is a bad thing.
I will close this bug report and add a feature request to be able to add raw HTML in the compose window.

I don't know how to solve your problem right now.

Regards.

**Comment by bachu** [comment]
I had never used WYSIWYG before, but now I made it work perfectly.
Thanks.
