### ISSUE TITLE
Can´t Delete Mails

### ISSUE THREAD

**Issue by bachu** [soonick/poMMo#35]
Hi
I check the mails I want to delete and press Delete Checked Mailings
A pop-up windows appear and asks me if I´m sure to delete... I pressed YED
A pommo window opens with the number 5 and nothing else happens.

Thanks.
Bachu

**Comment by soonick** [comment]
I was not able to replicate the issue. Are you using the latest version?

If so, please provide specific details to reproduce.

Thanks

**Comment by bachu** [comment]
I downloaded the zip file from the download button on source.

I just sent a couple of test messages, I got to History, check 1, or 2, or all the mail and press on DELETE, I confirm I want to delete then and a window that says pommo opens and nothing else happens.
I wait a while... nothing happens. I close the window, refresh, and the mails are still there.
I logout, login back again, the same.

**Comment by soonick** [comment]
I am gonna look into it. Which browser an OS are you using?

**Comment by bachu** [comment]
I tried it only on firefox for mac.

**Comment by jamesarbrown** [comment]
Yes firefox and Linux also the same... a 5 in the box and no mail deleted

The code is commented out in ajax/history.rpc.php

```
case 'delete' :
    echo 5;
    /*$deleted = Pommo_Mailing::delete($mailingIDS);
    $logger->addMsg(Pommo::_T('Please Wait').'...');

    $params = $json->encode(array('ids' => $mailingIDS));
    $smarty->assign('callbackFunction','deleteMailing');
    $smarty->assign('callbackParams',$params);*/
break;
```

I have uncommented as follows

```
case 'delete' :
    echo 5;
    $deleted = Pommo_Mailing::delete($mailingIDS);
    $logger->addMsg(Pommo::_T('Please Wait').'...');

    $params = $json->encode(array('ids' => $mailingIDS));
    $smarty->assign('callbackFunction','deleteMailing');
    $smarty->assign('callbackParams',$params);
break;
```

And it worked... so now to wonder why it was commented out.

bachu... can you remove the comment marks out and try?

Its in ajax folder.

Thanks

James

**Comment by jamesarbrown** [comment]
Soonick,

Do you want this code re-instating for now and see what goes?

James

**Comment by soonick** [comment]
Hello James,

If you tested it and it fixes the problem then we can close it for now. If it causes issues we can look more deeply later. Is the "echo 5" in there necessary?

Make the commit and let me know so I pull you changes.

Thanks

**Comment by jamesarbrown** [comment]
I have commited this and the upgrade issue
