### ISSUE TITLE
More personalized URLs

### ISSUE THREAD

**Issue by bachu** [soonick/poMMo#38]
Hi again, 

I was thinking that it would be great to have the possibility to make more personalized html.
From the setup panel we can find Success URL and Confirmation URL

but what about:
· Error URL... for example when your address was already submitted
· unsuscribe URL. I think this one is as important as Success URL.

I´m not a developer, so I just can bring up ideas and try different stuff.
¡I´m very interested in colaborating with soonick´s pommo!

Thanks,

**Comment by soonick** [comment]
Hello Bachu,

I appreciate your input to make poMMo better.

I really haven't tried the URL options in the setup panel. What happens now if you try to subscribe when you have already subscribed?

About the unsubscribe link I think you can create a template and add a link to any page you want. Or where do you want that link to appear?

Thanks.

**Comment by bachu** [comment]
Hi Soonick!

I configured a pommo installation so you can try what happens when you try to suscribe twice.
http://www.lunaticsmailing.com.ar/pommo.html

I can change the html you go to when you make your first suscription. That URL is configured from the setup menu.

But I can´t change the URL that appears when you try to suscribe twice. I think it would be great to have this function.

About unsuscribe, when you click on the link to unsuscribe it sends you to a URL (that can´t be modified from the admin panel), that asks you if you want to change your mail or to unsuscribe.
I think it would be very useful that when users click on the unsuscribe link to automatically delete them from the database and send them to a custom URL.

About what you said "About the unsubscribe link I think you can create a template and add a link to any page you want." where can I find that?

Thanks a lot!

**Comment by soonick** [comment]
Hello bachu,

That functionality seems too specific to address here. All that functionality can easily be done with a little code, and probably isn't what must pommo users want.

Making those changes would affect a lot of users that are used to how pommo works.
