### ISSUE TITLE
Remove smarty

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#40]
Smarty is hard to learn. It would be easier for new developers to use PHP as a templating language.

**Comment by jamesarbrown** [comment]
Hi Soonick,

I was looking at Smarty and its not that bad, but then I am used to JSF. Yes I can see it can be a bit of a headache switching between the tpl and php.

Have you had chance to create some form of template structure as basis for entire project?

James

**Comment by soonick** [comment]
Hello James,

I don't think a template engine is necessary.
I think the views of an application should not contain logic and should be very easy to understand. The most that someone should use in a view is helper functions, loops, conditionals, and inclusions of other views.

Having to learn smarty to be able to understand pommo is something that has been taking developers away from helping and since they already know php, using a php templating system makes the most sense.

I haven't thought of a templating structure, but let me know if you have any ideas.

Let me hear your thoughts.

**Comment by micdech** [comment]
Try RainTPL. Only 8 tags to learn... very easy and fast template system.

Only 2 file to include.

But, like Adrian, i think a template engine is not so much necessary....

**Comment by Renegades** [comment]
I am NOT a programmer at all and sure, my PHP ... better not talk about it, Yet, I managed to do a major re-design on both, the admin as well as User pages. Add to it, I think "smarty" system is even better to have it. But then again, as said, I am not a professional programmer so I may be unaware of many other issues revolving around smarties.

**Comment by soonick** [comment]
Smarty has been completely removed from poMMo. If you find that I introduced any bug in the process please let me know and I will try to fix them ASAP.
