### ISSUE TITLE
test email always txt/plain

### ISSUE THREAD

**Issue by thinkround** [soonick/poMMo#41]
Hi there, 

I installed the latest master of pommo and found one problem: When sending out test versions of a sendout, the content/type is txt/plain instead of txt/html, which is not helpful for testing. I don't know where to start looking for the source of the problem. Can anyone reproduce this error?
Cheers, Michael

**Comment by thinkround** [comment]
Additional info: 
If I leave the text version of the email blank I get the html version with content-type txt/plain.
If I leave the html version blank I get nothing.
If I fill in something in the text version I get the html version with content-type txt/html.

This should be I think:
If I leave the text version of the email blank I get the html version with content-type txt/html.
If I leave the html version blank I get the text version with content-type txt/plain.
If I fill in something in both versions I get the html version with content-type txt/html or the text version with txt/plain, depending on user preference.

**Comment by soonick** [comment]
Thanks for reporting this problem. I will try to look into it soon.

Regards.

**Comment by jamesarbrown** [comment]
Yes I can reproduce..... test mails sent plain text, proper mailings html.

As workaround

For now i created a field "Receives Test Mails" as checkbox default not checked
Create group "Receives Test Mails" based on checkbox
Select yourself in mail list, update subscriber for test mails to receive them.

Create a mail to test group, ensure it only shows 1 recipient and send.

James

**Comment by wesdollar** [comment]
I resolved this issue with the following:

file: lib/phpmailer/class.phpmailer.php

Line 65 -> set $contentType = 'text/html';

We send HTML only, so I did not test the effect this might have on text only mailings.
