### ISSUE TITLE
[[!weblink]]

### ISSUE THREAD

**Issue by 4rthr** [soonick/poMMo#42]
the [[!weblink]] special link doesn't work in my templates...

**Comment by soonick** [comment]
Thanks for reporting this problem. I will try to look into this soon.

**Comment by soonick** [comment]
Hello 4rthr,

What is the problem you are having? Are you not able to include the link? or the link doesn't take you to the correct page?

Regards

**Comment by 4rthr** [comment]
Hi soonick!
The links doesn't take me to the correct page.
Cant see the mailing in web, the link takes me to subscription page.

Thanks, mas.

**Comment by jamesarbrown** [comment]
You need to go into the configuration, mailings tab and set "public mailings on"

I have tried and works for me.

Maybe need to change to a "feature request" to make things more clearer.

No Idea how it works but something to do with  this redirect in mailing.php
$config = Pommo_Api::configGet('public_history');
if($config['public_history'] == 'on') {
    Pommo::init(array('authLevel' => 0));
} else {
    Pommo::redirect('login.php');
}

James

**Comment by soonick** [comment]
Thanks James. I agree with you, this is not a bug, but you are also right in that we should make this clearer. I should document this in some way

Can you try what James said 4rthr?

**Comment by soonick** [comment]
I tried James suggestion and it works.

Thanks.

**Comment by 4rthr** [comment]
hey guys! working perfect!

Thanks for helping!
