### ISSUE TITLE
SQL Issues sql.schema.php

### ISSUE THREAD

**Issue by jamesarbrown** [soonick/poMMo#43]
Hi Soonick,

[root@jblaptop pommo]# rpm -qa |grep mysql
mysql-libs-5.5.13-1.fc15.x86_64
mysql-utilities-1.0.1-0.5.2.34.fc15.noarch
mysql-5.5.13-1.fc15.x86_64
mysql-workbench-5.2.34-1.fc15.x86_64
mysql-server-5.5.13-1.fc15.x86_64
mysql-connector-python-0.3.2-2.fc15.noarch
php-mysql-5.3.6-2.fc15.x86_64

When installing a fully clean system causes :-
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(14) NOT NULL, `time_registered` datetime NOT NULL, `flag` tinyint(1) NOT NULL d' at line 1

Which is caused by (I think)
--  SUBSCRIBERS

CREATE TABLE :::subscribers::: (
  `subscriber_id` int(10) unsigned NOT NULL auto_increment,
  `email` char(60) NOT NULL default '',
  `time_touched` timestamp(14) NOT NULL,
  `time_registered` datetime NOT NULL,
  `flag` tinyint(1) NOT NULL default '0' COMMENT '0: NULL, 1-8: REMOVE, 9: UPDATE',
  `ip` int unsigned NULL default NULL COMMENT 'Stored with INET_ATON(), Fetched with INET_NTOA()',
  `status` tinyint(1) NOT NULL default '2' COMMENT '0: Inactive, 1: Active, 2: Pending',
  PRIMARY KEY  (`subscriber_id`),
  KEY `status` (`status`,`subscriber_id`),
  KEY `status_2` (`status`,`email`),
  KEY `status_3` (`status`,`time_touched`),
  KEY `status_4` (`status`,`time_registered`),
  KEY `status_5` (`status`,`ip`),
  KEY `flag` (`flag`)
);

And needs amending to :-

CREATE TABLE :::subscribers::: (
  `subscriber_id` int(10) unsigned NOT NULL auto_increment,
  `email` char(60) NOT NULL default '',
  `time_touched` timestamp NOT NULL,
  `time_registered` datetime NOT NULL,
  `flag` tinyint(1) NOT NULL default '0' COMMENT '0: NULL, 1-8: REMOVE, 9: UPDATE',
  `ip` int unsigned NULL default NULL COMMENT 'Stored with INET_ATON(), Fetched with INET_NTOA()',
  `status` tinyint(1) NOT NULL default '2' COMMENT '0: Inactive, 1: Active, 2: Pending',
  PRIMARY KEY  (`subscriber_id`),
  KEY `status` (`status`,`subscriber_id`),
  KEY `status_2` (`status`,`email`),
  KEY `status_3` (`status`,`time_touched`),
  KEY `status_4` (`status`,`time_registered`),
  KEY `status_5` (`status`,`ip`),
  KEY `flag` (`flag`)
);

Ie the timestamp column has a width (14) which as far as I can make out is what MySQL is fussy about.

James

**Comment by soonick** [comment]
Hello james,

You are right, it is weird to declare a timestamp field with a width of (14).
I will try to emulate your system with the information you provided and if I can recreate the problem it should be easy to fix.

Thanks

**Comment by soonick** [comment]
Hello james,

Which version of pommo are you using? if you downloaded it from here, can you tell me the commit number?

Thanks

**Comment by jamesarbrown** [comment]
Didn't write down the commit.... was a git clone from yesterday 13 Jul 11, so as far as I can make out the current one.

James

**Comment by jamesarbrown** [comment]
Have amended this in fork... can it be merged?

EDIT Sorry... accidentally closed.... did not mean to.

**Comment by soonick** [comment]
I received your pull request. Added a comment on the modifications of ajax/ajax.smtp.php. I think there are some modifications to the file that are not related to any of the issues you resolved.

**Comment by soonick** [comment]
Merged James Fix.

Thanks.
