### ISSUE TITLE
weblink should tell visitor when link is not available

### ISSUE THREAD

**Issue by soonick** [soonick/poMMo#45]
On ticket #42 there was a confusion about the [[!weblink]] macro not working.

The problem is that when the web view is not available (Configured in pommo's preferences) the visitor is redirected to the login page. It would be clearer for the user if a message was shown telling her that the web view is not available at the time.

**Comment by Renegades** [comment]
First - agree totally

Second ...  [[!weblink]] - where is it in preferences? I don't seem to have it

Third ... similar to  [[!weblink]], is there or if not, can there be something like  [[!send this to]] like a referral? Meaning, if the receiver of a campaign thinks it could benefit their friend, colleague, he/she could just click on this and then (already pre-filled with some text) his/her email client would open up to send it (forward) to their friend(s). All they would need to be left to do is select their friend's email address, That's it.
