### ISSUE TITLE
Doesn't ask me for a login and password after setup

### ISSUE THREAD

**Issue by clumzy** [soonick/poMMo#49]
Hi, and first of all, thanks for maintaining poMMo !

WHenever I try to install poMMo on my local server, it nevers asks me for a password or login :
I launch the website, it asks me the database information, calls out an error and asks me to edit the config.php file. I do it, and when I go to the website for the second time it asks me for a login and password, which I didn't setup !
Do you know what is the cause of this issue ? 
Please let me know !

**Comment by clumzy** [comment]
Actually, nothing is even written in the database

**Comment by jamesarbrown** [comment]
Do you have more info on the error that was thrown?

**Comment by soonick** [comment]
Try making the folder where you placed pommo and the cache folder writable

**Comment by clumzy** [comment]
Actually, sorry for my mistake, it's working just fine !
I may have forgotten to make my folders writable.

Thanks again for your help and for maintaining poMMo !
