### ISSUE TITLE
faulty redirect [new group]

### ISSUE THREAD

**Issue by armitage** [soonick/poMMo#5]
After creating a new group, pommo redirects to the group edit page but redirects with a relative path creating an url like http://example.com/poMMo/admin//poMMo/groups_edit.php?group=2 which is obviously broken.

cheers
milan

**Comment by soonick** [comment]
Thank you for reporting this bug. I will let you know when I commit the solution.

**Comment by soonick** [comment]
Hello, I just fixed this bug, but I am going to take it to the master branch when I finish working on the attachments section.

**Comment by soonick** [comment]
There are other redirects that cause problem
