### ISSUE TITLE
import issues pommo 16.1

### ISSUE THREAD

**Issue by imanordin** [soonick/poMMo#53]
Hi,

I have just installed pommo version 16.1 and i have import issues.

I have tried two things. 

1) Import using csv

2) Import using "list of email addresses"

Both gives me this error. 

After this step :

---

1 non-duplicate subscribers will be imported. 0 were ignored as duplicates.

Notice: Imported subscribers will be flagged to update their records

---

I clicked "YES"

Error: After clicking yes. It keeps showing "updating" and nothing happens.

Why is it so ?

I have checked with my web hosting company and they told me the server im on now is compatible for this script. 

I have tried sending test emails to myself and it works fine. 

The only problem now is i cant seems to find a way to add email addresses. 

Any help would be awesome. 

Thanks

**Comment by imanordin** [comment]
Is this dead website ?

**Comment by imanordin** [comment]
help!...

**Comment by soonick** [comment]
Sorry for taking so long to reply. I was very busy this past weeks.

Please let me know if this is still an urgency to you and I will try to dedicate some time to fix it.

Regards,
Adrian

**Comment by imanordin** [comment]
Hi,

Thanks Adrian.

I have not solve the issue actually. Can i know what should i do. Becasue i am not able to import any customers from csv file. Im trying to add around 10k emails each email is on 1 row.

The loading java arrow keeps turning but after waiting 2 days i know its not working.

Thanks for the help man.

**Comment by soonick** [comment]
Can you send me an example of the file you are using?

Don't send me your whole 10K file. Just include a couple of customers so I can make sure the format of the file is correct.

Regards

**Comment by cryptonics** [comment]
I was having this same issue and was banging my head against the wall.  The solution at least on my system was actually within the CSV file.  If there is a space anywhere then it'll cause the script to fail.  

Failed CSV Example:

Email@website.com ,first_name,last_name

Working CSV example:

Email@website.com,first_name,last_name

The difference is subtle, but huge.  I actually took the liberty of logging in and testing it on the above URL and a test CSV with only 14 addresses on it loaded just fine.

**Comment by micdech** [comment]
Hi imanordin,

seems you are using an old version of pommo.
Have you download new version from github? or you do it from pommo.org?

Regards :)

**Comment by imanordin** [comment]
Hi 

How do i download the new version from github ? I am using version 16.1 and it is the latest version according to my host. I am still unable to to upload email. sickening. 

Is it a must to have first name and a last name ? Can anyone send me a template CSV file . 

Would appreciate the help here. Thanks!

**Comment by cryptonics** [comment]
I tested it again using just a single field with email addresses and had no issues.  What fields are you trying to import?

**Comment by imanordin** [comment]
@cryptonics 

hi, i tried again. and it works! thanks. problem solved!
