### ISSUE TITLE
easy/professional mode

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#55]
One of the big strengths of poMMo is its simplicity. We should reinforce this by creating an easy mode (with nearly no settings to change - just write email and click 'send') and a professional mode (with all the advanced settings like speed throttling and so on).

What do you think about it?

**Comment by soonick** [comment]
Hello Manuel,

I agree with you in that one of poMMo's strengths is simplicity. But I don't think that adding an option to make it simple will really make ti simpler. The options are in there for the people that want to use them. Simply writing an e-mail is already pretty easy to do.

Let me know your ideas about the implementation of this.

**Comment by ghost** [comment]
Hi!

When I first openend pommo after installation (3 years ago) I had to understand too much things. I went to the admin setup and played a bit with the settings without understanding them really. After a few minutes, I had to delete the config, because it did not send Mails any more and I didnot know how to solve the issue.

This is how I came up with the idea. But I also think, that this might be a pommo 2.0 feature - for know there are more important things to do... :-)

**Comment by soonick** [comment]
I don't think this feature is really needed yet. The default settings work pretty well for most of the cases, so there is no need to change anything in throttle if you don't want to. If you need more control about what you are doing, then you have the options in the admin panel to make it happen.

If more people agree with you about this feature we can open this issue again and discuss about it.
