### ISSUE TITLE
PHP Invoked Shutdown Function

### ISSUE THREAD

**Issue by luntzel** [soonick/poMMo#58]
**\* ERROR THROWN **\* PHP Invoked Shutdown Function. Processor Abruptly Terminated. See ERROR_LOG IN WORK DIRECTORY. Runtime: 46 seconds.

All that is in the log is 

"<?php die(); ?>"

Specs: 
PHP 5.2.4-2ubuntu5.19

Latest Pommo from this repo (https://github.com/soonick/poMMo)

We've always had to hit 'resume' like 50 times just to complete the mailing, which requires a bit more manual interaction than desired. Thank you in advance for your help.

**Comment by luntzel** [comment]
Also: it appears as if its an issue with the data that is in the subscriber email field, because its so sporadic and it doesn't appear to halt in a regular pattern which would denote a resource issue.

**Comment by Alexcricket** [comment]
Hello luntzel, how are you?  I have the same problem here "**\* ERROR THROWN **\* PHP Invoked Shutdown Function.". Do you know how to fix it?

Thanks

**Comment by luntzel** [comment]
I clearly did not get any response on this from the developers. I upgraded to the lastest version, with the hope that it would be fixed. No such luck. Sadness.

**Comment by Alexcricket** [comment]
This is really sad indeed! :-(

**Comment by anhle82** [comment]
Hi, does anyone know how to fix that issue yet? I got the same problem today and been trying to figure out what cause it.

**Comment by soonick** [comment]
I'm working on trying to reproduce this issue

**Comment by soonick** [comment]
Sorry for taking so long to look at this issue. Please let me know if this doesn't fix your problem.
