### ISSUE TITLE
Mailing Status Frozen

### ISSUE THREAD

**Issue by nightm** [soonick/poMMo#6]
If the current fall, when the server is reopened Status Mailing is Frozen, so I need to resume, witch can be annoying. A cron maybe it can solve this problem.

**Comment by soonick** [comment]
Im sorry, I didnt understand the bug report. Can you try to explain it in other words.

**Comment by nightm** [comment]
Let's say I have a mail server with pommo. I put to send a couple of emails but the server locks. After a restart the server, pommo's mailing status is Frozen, so I need to resume to send the last emails in the list.

**Comment by soonick** [comment]
Might be a server Issue. Can you send me some steps to try to reproduce it?

**Comment by llynix** [comment]
My poMMo also does the frozen thing.  Seems random.  Last time it didn't do it at all but until the very end.

**Comment by dmemarian** [comment]
My pommo freezes every so often as well and sometimes I can't resume, like now. I can send test emails and I've checked for spawning and it works but when I click on resume when pommo is frozen it spends some time and then goes back to showing frozen. It's frustrating when you're halfway a database of 70k...and the only thing you can do is restart the entire email broadcast :(

**Comment by soonick** [comment]
Hello,

Bug #7 addresses the problem with the resume button. I will try to fix it, but I have been busy these days.

**Comment by dmemarian** [comment]
Hi Soonick!

I understand! You're doing a great job and I'm very grateful! Thank you.
