### ISSUE TITLE
no setup after a fresh install - can't login

### ISSUE THREAD

**Issue by sm4rtins** [soonick/poMMo#61]
I'm in trouble that I can't login because I couln't create an user and password.
No setup was shown after install, it goes direct to logins page.

I thought that it could have a default user and password, but I didn't find on any documentation.
Have already tryed the same user as mysql db, but doen't work neither.

I be very glad if someone could help me.

Thank's folks!

**Comment by sm4rtins** [comment]
database problem, recreate all again.But now my problem is that when I change the language to pt-br it doesn't load the page anymore.Getting crazy with this. :s

Any sugestions ?

Thank's.

**Comment by soonick** [comment]
What do you mean by it not loading? Do you get any error message? Do you get anything?

**Comment by Renegades** [comment]
same thing here- goes straight to the login page (no installation process of poMMo at all) and O tried twice.
I try now the original poMMo and there it is all OK. BTW I used a complete new DB so I am not sure why the DB should be a problem cause for this version ?? (thinking)

**Comment by aleray** [comment]
I can't connect too using your fork and my db created with the original version of pommo. I have noticed that the login method queries on the table "users" which is not present in my db. Is there any database update script around?

Thanks

**Comment by soonick** [comment]
Hello,

I created a set of sql commands that will easily upgrade your DB from Aardvark PR16.1 to my latest version. The sql file has some place-holders that you should replace so it works for you.

You can find this file on sql/upgrade.sql on my repository.

This should fix your problems, so I will close the ticket. If you run into any problem feel free to reopen it and add more information.

Regards,
Adrian

**Comment by aleray** [comment]
Hi Soonick,

 It fixed the problem indeed; thank you very much for taking care of this.
