### ISSUE TITLE
Mail tracking

### ISSUE THREAD

**Issue by chico76** [soonick/poMMo#63]
Hello.
I'm testing this nice pice of software, and the only thing I'm really missing is tracking of who has opened the mail.
In the {$prefix}_mailings_hits table i have seen that you store both mail_ID and user.
Sadly I have not coded for 15 years, but I've started a quick'n'dirty to use this  data (i will just export a CSV file for the selected newsletter)
This is a featue I think is very important for this type of software.

**Comment by Renegades** [comment]
Absolutely agree. ;-)

**Comment by soonick** [comment]
I will add a button to the mailings history page (mailings_history.php). To export a list of the people that have opened the email.

**Comment by asciiker** [comment]
Hello,

I run a Mail Marketing company and I have been using this version of PoMMo pretty intensively over the past 45 days.

Thank you so much for your work! I would like to help however I can. I am more of an admin than a developer but I get around.

Question:  is tracking working yet?  I have ran some tests, and it seems to add an image link to the footer but it fails to find it with a 404.

(I'm using personalized mailing lists, could this be the reason?)

Thanks again!
Hugo
Kimera

**Comment by asciiker** [comment]
Hello again, it was my mistake. Problem was the missing .htaccess on my implementation.

Cheers!
Hugo
Kimera

**Comment by soonick** [comment]
I'm glad you found the solution :)
