### ISSUE TITLE
Date field not usable

### ISSUE THREAD

**Issue by Renegades** [soonick/poMMo#65]
I added a DOB field (date of birth) and  face some major issues with it.
1. 
   it adds a calendar picker but it allows me only to pitch days from today onwards. this would mean, al my subscribers weren't even born yet (funny)
   2.
   I get deprecated PHP code errors about a wrong DST...?
   3.
   the (update) email I get sent shows some really funny and weird numbers (am on a Mac and have no idea how to adjust the code of poMMo so the date would actually show the date (it is OK in the database)
   4.
   One of the main ideas for me to have the DOB field is - so I could be reminded on who's birthday would fall into, e.g this week or month. But, I can't even use poMMo's admin filter under "manage subscribers)
2. 
   updating my DOB (as the actual user) doesn't work neither. Even if I follow the system's requested input (YYYY/MM/DD) it would not allow me to update. The "add" button stays deactivate)
   At least, the system could tell a user what format to use and if wrong, throw an error message but everything seems to ne just dead.

So I wonder what this "date" field is good anyway. As it is now it seems to be a complete waste. which would be the biggest pitfall since DOB is one of the best tools to stay in touch with your subscribers. How nice is it if you get a nice birthday greeting but with poMMo this seems years away from. ,-(

**Comment by Renegades** [comment]
OK, so this time DOB thing seems to get from bad to worse.

I exported a sample CSV, the dates show as; e.g 18 Nov 1975.
If I follow exactly this sample, or any other way, nothing gets imported at all. The only format I can use is 18/11/1957, that would import it. Funny though, the dates will then be randomly changed into some extreme ridiculous time, like 19/12/2013 ...
Hello, we are still in 2012 anyway, but why must these people all be born in the future now! ???
If that's not enough,
I change it manually again in the admin section - find, but what if I have ... a LOT like literally, thousands? No fun.

Anyway, I changed a few and did another export. All OK.

Now I do absolutely "Nothing" - I just take the entire CSV as I exported it and import it again. Guess what. Noe it doesn't take the date again, it just strips all date data.

Hmmm, as I said, better don't have this option for adding anything like a dat. It's catastrophic as it is. I just try to figure out what ida was in why adding it like this in the first place? hmmmmmmmmmmmm? ROFWRE ;-)

There are quite a few other bugs which makes it (it all looked very interesting and promising at the beginning) almost impossible to have any use of poMMo. 

I have to be fair. If you just run a simple mass mailing and you don't care about anything - just want an email address so you can tens of thousand of email and bother the people out there - like Facebook or linkedin... (official spam) then good.

If you want, however, collect certain data so you can send targeted newsletter based on your client's interests, field of work, etc. etc. then poMMo is certainly Not the way to go. 

Which again, brings me up to raise the most valid question... who adding all this options of extra fields, ester groups etc. if in the end, you can't bring it to a proper use! ??? 

ROFWREIAD ;-)

**Comment by soonick** [comment]
I was unable to reproduce this issue.

Please provide detailed instructions of what you are doing, what is the expected result and what is the actual result.

**Comment by Renegades** [comment]
no problem, I solved it. I deleted the date picker, it's rubbish.

BTW, what's your question "what are you doing" ...?  I installed that pommo and the date picker is automatically added.  Where am I coming in by possibly doing anything a=other than trying to use this damn thing? Funny questions and assumptions you have.

BUT, as said, You solve it on your side by "just closing the issue" I solve it on my side by just deleting the crap!

Sorry for my sharp tone but you developers have a funny way in dealing with all your bad hacks and you'd still be arrogant enough to call yourselves "professional programmers" Apply for a programming job in my company and maybe I allow you to clean my computer screen!

Norbert Harms
norbertharms_chinabiz21@aol.com

-----Original Message-----

**Comment by soonick** [comment]
Sorry again,

but without detailed instructions on how to reproduce it, I can't help you.

Regards,
Adrian

**Comment by Renegades** [comment]
I really don't know what to say, Adrian.
What can I possibly do or have done wrong when installing it?

All I can say (and obviously others face the same problems) that the form displays a date picker and this date picker goes forward in time only. Hence if I open the form today and would like to input a DOB, it can only be a date starting from today, meaning, I was either born today or will be born tomorrow, or so on... but never the date when I actually "WAS" born...!

So what am I possibly doing wrong? Do I press the wrong button when I open the form? Am I suppose to open the form at a specific time only? Do I need to push my computer into the right position? What else can I do wrong so the date-picker wouldn't allow me to pick a date in the past? Maybe I use the wrong fingers?

I don't really know why this is so complicated to understand, the difference of "back in time and forward in time".

If you can't reproduce it, well, I have no answer for that neither except, I tried 3 installs of the ONE and the same version (but downloaded from different locations) I did notice though, there is a heck of a lot of different poMMo downloads and version floating around and one would never know which could possible work the best. 

I said it before and stick to what I said. The original writer of the script must obviously have a very good reason why he abandoned his own script! It's a pity, because it had potential but I also realize, it's really dying off fast! That, too, has it's reasons, very obvious!

Norbert Harms
norbertharms_chinabiz21@aol.com

-----Original Message-----
