### ISSUE TITLE
foreach() error message

### ISSUE THREAD

**Issue by alankessler** [soonick/poMMo#68]
Hello,

I just installed poMMo fresh and for the first time. I'm getting the following error messages or similar on most of the forms:

Warning: Invalid argument supplied for foreach() in [REDACTED]/pommo/themes/default/subscribe/form.update.php on line 42

**Comment by soonick** [comment]
Thanks for reporting this bug.

Can you please tell me what you were doing (or trying to do) before you got the error?

**Comment by alankessler** [comment]
I had created a database, set up poMMo, added myself as a user, sent a 
test email from the default template, and clicked the unsubscribe link.

The error comes up right after the "verify new email" box on the 
unsubscribe page.

**Comment by cd45** [comment]
Hi this issue is on the form.update.php on line 42 it occurs when you go to update.php to update your email or unsubscribe

please advise how to fix this

**Comment by cd45** [comment]
ok i found if i add this code to top of     form.update.php      I can hide the warning as the page seems to work

<?php

ini_set( "display_errors", 0); ?>
