### ISSUE TITLE
'Send Test' not working consistently

### ISSUE THREAD

**Issue by chrshea** [soonick/poMMo#69]
When I use the 'Send Test" facility, sometimes it works and sometimes I just get html with embedded text:

``` html
<p><style type="text/css" media="all">

/* base styling */

div.pommoMailing {

  background-color: white; /* background color */
  color: #333; /* text color */
  width: 100%;
  padding: 6px;

}

etc.
```

So far, I haven't seen a pattern to it. Once it starts doing this for a particular mailing, it seems to continue (except maybe if I close everything down and start over). I am using Yahoo Mail and that is where I am seeing the test displayed. This doesn't seem to affect the actual mailing because it has consistently worked ok even when the test didn't work.

I didn't see anything about this in the list of Issues. I don't have the very latest build so I will have to try that and see if it makes any difference.

Chris

**Comment by soonick** [comment]
Hello,

There is already an issue open for this problem:
https://github.com/soonick/poMMo/issues/41

Please follow up on that thread with any extra information you may have.
