### ISSUE TITLE
missing textarea field feature

### ISSUE THREAD

**Issue by pommoficious** [soonick/poMMo#71]
hi soonick,

thanx for help.
actually im just missing textearea as field or label option not only text input.
sure, for the implemented form its no problem. :) hard coded.

but i cant assign textarea id to for the update.php actually for form.update.tpl
i would need something like this
<textarea id="field11" name="d[11]" rows="3" cols="33" maxlength="255"></textarea>

do you know a workaround how i could accomplish that?

thank you very much
sincerely

**Comment by soonick** [comment]
Hello pommoficius,

Thanks for reporting this issue.

Can you explain a little more what you are trying to achieve? This information would be useful to help you:
In which url will the functionality be added? (Which screen?, Which option?)
What benefit will the user get from this functionality? (An example would be good)

Thanks,
Adrian

**Comment by pommoficious** [comment]
hello adrian,

actually, it would be nice to have additional the option to add a textarea instead only just a textfield.
for people so they can write messages with line breaks.
when generating the formfields..

benefit would be textarea where people can write longer textes with line breaks, not a textfield with 
endless text on one line.

best regards
pommoficious

On 02.06.2012, at 04:06, Adrian Ancona Novelo wrote:

Hello pommoficius,

Thanks for reporting this issue.

Can you explain a little more what you are trying to achieve? This information would be useful to help you:
In which url will the functionality be added? (Which screen?, Which option?)
What benefit will the user get from this functionality? (An example would be good)

Thanks,
Adrian

---

Reply to this email directly or view it on GitHub:
https://github.com/soonick/poMMo/issues/71#issuecomment-6074222

PLATZHALTER GmbH
Gestaltung und Mac Support

Thomas Mettler
Grubenstrasse 11, 8045 Zürich
macsupport@platzhalter.ch
http://www.platzhalter.ch
044 240 09 66

**Comment by soonick** [comment]
Hello pommoficious,

There is a field type "comments" that does what you need.

Regards,
Adrian
