### ISSUE TITLE
*** ERROR THROWN *** PHP Invoked Shutdown Function

### ISSUE THREAD

**Issue by anhle82** [soonick/poMMo#72]
Pommo stops sending mails after few minutes and give me the below error

18:10:31 > **\* ERROR THROWN **\* PHP Invoked Shutdown Function. Processor Abruptly Terminated. See ERROR_LOG IN WORK DIRECTORY. Runtime: 27 seconds.
Started Mailing #16

Can someone show me what was the cause of this please? Thanks

**Comment by soonick** [comment]
Hello anhle82

Thanks for reporting this issue, I will try to look at it when I get some time.

**Comment by soonick** [comment]
Hello anhle82,

There is already a ticket open for this issue. I will close this one so we can have a central point for the problem.

Issue #58

Thanks.
