### ISSUE TITLE
modify notification output fields order? - solved

### ISSUE THREAD

**Issue by pommoficious** [soonick/poMMo#73]
hello,

actually the notification option sends mail to the admin, when user subscribes, unsubscribes, updates etc...
how or where would it be possible to modify the notification output which will be sent to the admin?

because now it sends the notification with the form fields in alphabetical order which is irritating.
where would it be possible to set the order the same way as it is set on the setup fields or subscriber form?

unfortunately i dont find the php file or tpl to modifiy the notification output.

can you maybe help me out

thanks for help
sincerely
pommoficious
:D

**Comment by soonick** [comment]
Hello pommoficious,

Thanks for reporting this issue, I will try to look at it when I get some time.

**Comment by pommoficious** [comment]
hi soonick, thank you anyway!

i found the solution!!
change byName from true to false in the file /inc/helpers/fields.php on line 137

```
function & get($p = array()) {
    $defaults = array('active' => false, 'id' => null, 'byName' => false);
    $p = PommoAPI :: getParams($defaults, $p);
```

then every foreach error msg output and also the reporting mail you receive when someone subscribes or updates his profile, will sort the order by field ID
no alphabetic sorting. heureka!!
:D

**Comment by soonick** [comment]
Hello pommoficious,

Thanks for providing the fix for this issue. I will be adding it to the repository soon.

Thanks.
