### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Andrew-Jordaan** [soonick/poMMo#75]
Hi 

I am trying to install cpommo on a shared server to replace obsolete pommo that was used for years pulled from original pommo website.

Problem I am having is the server seem to see the index.php as a virus and deletes it.

Here is the comment I managed to catch from  a filezilla : " Response:  550 Virus Detected and Removed: Atomicorp.suspicious.mysqlselect.POST.20111212224703.UNOFFICIAL "

any help would be most appreciated.

thanks 

Andy

**Comment by soonick** [comment]
Hello Andy,

I don't think there is anything we can do about this. Probably your hosting company can help you with this issue.

Regards,
Adrian
