### ISSUE TITLE
Group Select Error

### ISSUE THREAD

**Issue by Exemcs** [soonick/poMMo#76]
Hi

I installed ver 135673e, created two groups of Active Subscribers and found I could not properly select either group.

I found a solution by editing themes/default/admin/subscribers/subscribers_manage.php at line 75:

<option value="2"
<?php
    if (2 == $this->state['status']) /\* Changed 1 to 2 */
    {
        echo 'selected="selected"';
    }
?>><?php echo _('Pending'); ?></option>

The original code resulted in there being two 'selected' items in the View drop-down list.

Regards

Exemcs

**Comment by soonick** [comment]
Thanks for reporting this issue and providing the solution to it.

I will add your fix and close this ticket.
