### ISSUE TITLE
Throttle not working?

### ISSUE THREAD

**Issue by muxmix** [soonick/poMMo#77]
Email throttling doesn't seem to work.
I tried to change the email per hours value but when I click "apply" it always goes back to default (60 per hour).
Since I have 20K addresses it would take ages ...

**Comment by muxmix** [comment]
UPDATE:
I looked into config table and settings are saved.
It's the Ajax panel that doesn't seems to be able to read the current saved values.

**Comment by soonick** [comment]
Hello muxmix.

Thanks for the update. I will try to take a look at why the panel does not update when I have some time.
