### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#78]
I'm rather frustrated... pommo-wise anyway :) I've tried every way possible, but I can't log into my pommo installation (before and after updating to the latest version found on here).
I've tried manually resetting the password via phpMyAdmin via chechsum generator
I've tried manually resetting the password via phpMyAdmin via "update pommo_config set config_value = MD5("desired password") where config_name="admin_password";" query (yes, I entered my own password)
I've tried manually resetting, but just get a "Pommo_Helper_Messages::sendMessage() - subject or body empty" message, and the email never gets to me.

Any help/suggestion would be greatly appreciated. My apologies if this was posted to the wrong section, I'm new to Github.

Installation: http://www.vaughangardiner.co.za/scriptz/nuusbrief/

**Comment by soonick** [comment]
Hello gennath,

Try using the script sql/upgrade.sql. Please open the file before running the statements because there are some modifications you need to make.

Let me know if this solved the issue. I will add this to the wiki so other people with the same problem can find it.

Regards,
Adrian

**Comment by ghost** [comment]
Worked like a charm! Thank you so much!

**Comment by nEON7** [comment]
When installing clear new version of Ur PoMMo -> 
I must update columns too, Just little thing that sql script is in pommo folder and u need to edit prefix + username + password before copying text inside to run script in MySQL, when it's done u can use it again.
