### ISSUE TITLE
Magic Quotes Runtime Problem

### ISSUE THREAD

**Issue by fatihcr** [soonick/poMMo#79]
Hi

i just wanna install pommo but i get some errors...

http://www.kozmar.com/mailing/install/install.php

Deprecated: Function set_magic_quotes_runtime() is deprecated in /home/kozmar.com/httpdocs/mailing/bootstrap.php on line 56 

My Server Properties: http://www.kozmar.com/info.php

how can i fix it?
thanks

**Comment by soonick** [comment]
Hello,

I will take a look at the problem, but just a question.
Is this message making it impossible  to install pommo?

**Comment by fatihcr** [comment]
no soonick, i installed with this problem.
everypage had this issue on top and something wrong every section on pommo
can you help me please?

**Comment by soonick** [comment]
What version of poMMo are you running?

**Comment by fatihcr** [comment]
all versions, i think that issue about php version or hosting values?

**Comment by soonick** [comment]
Hello,

You are right in that it may be something related to your version of PHP. The reason I ask is because my bootstrap file doesn't have line 56. Does your bootstrap file has that many lines?

**Comment by fatihcr** [comment]
yes its content of my bootstrap.php
line56: set_magic_quotes_runtime(0);

---

<?php
/**
- Copyright (C) 2005, 2006, 2007, 2008  Brice Burgess bhb@iceburg.net
- 
- This file is part of poMMo (http://www.pommo.org)
- 
- poMMo is free software; you can redistribute it and/or modify 
- it under the terms of the GNU General Public License as published 
- by the Free Software Foundation; either version 2, or any later version.
- 
- poMMo is distributed in the hope that it will be useful,
- but WITHOUT ANY WARRANTY; without even the implied warranty
- of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See
- the GNU General Public License for more details.
- 
- You should have received a copy of the GNU General Public License
- along with program; see the file docs/LICENSE. If not, write to the
- Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
  */

// Start Output buffering
ob_start();

// while poMMo is in development state, we'll attempt to display PHP notices, warnings, errors
ini_set('display_errors', '1');

// error_reporting(E_ALL); // [DEVELOPMENT]
error_reporting(E_ALL ^ E_NOTICE); // [RELEASE] 

// Include core components
require(dirname(**FILE**) . '/inc/helpers/common.php'); // base helper functions
require(dirname(**FILE**) . '/inc/classes/api.php'); // base API
require(dirname(**FILE**) . '/inc/classes/pommo.php'); // base object

// Setup the core global. All utility is tucked away within this global to reduce namespace
// pollution and possible collissions when poMMo is embedded in another application.
$GLOBALS['pommo'] = new Pommo(dirname(**FILE**) . '/');

/*
- Disable session.use_trans_sid to mitigate performance-penalty
- (do it before any output is started) [from gallery2]
  */
  if (!defined('SID')) {
  @ini_set('session.use_trans_sid', 0);
  }

// soft turn off magic quotes -- NOTE; this may break embedded scripts?
// clean user input of slashes added by magic quotes. TODO; optimize this.
if (get_magic_quotes_gpc()) { 
    $_REQUEST = PommoHelper::slashStrip($_REQUEST); 
    $_GET = PommoHelper::slashStrip($_GET); 
    $_POST = PommoHelper::slashStrip($_POST); 
}

// disable escaping from DB
set_magic_quotes_runtime(0);

// Assign alias to the core global which can be used by the script calling bootstrap.php
$pommo =& $GLOBALS['pommo'];
$pommo->preinit();
?>

**Comment by soonick** [comment]
Have you tried commenting that line?

**Comment by fatihcr** [comment]
which commenting line?
display errors?

**Comment by soonick** [comment]
Line 56. Can you try changing it from:

set_magic_quotes_runtime(0);

to

// set_magic_quotes_runtime(0);

**Comment by fatihcr** [comment]
i'm changed 

"ini_set('display_errors', '1');" to ini_set('display_errors', '0');

and its fixed thank you

**Comment by soonick** [comment]
Great!
