### ISSUE TITLE
Unable to send mails through external SMTP relay

### ISSUE THREAD

**Issue by rudyd-zz** [soonick/poMMo#81]
I have been trying to send emails from Pommo using an external SMTP server. However when I change the details on "Setup your SMTP servers" , it shows as unable to connect to external SMTP despite entering the right credentials. Any idea of how to get over this problem ?

**Comment by soonick** [comment]
Hello rudyd,

I have my poMMo setup using SMTP relay in an external server. This may be a bug we have to look into further. What authentication/encryption method are you using?

Thanks,
Adrian

**Comment by rudyd-zz** [comment]
Hey Adrian, 
Sorry forgot to update here. Had installed in shared hosting , later moved it to a VPS where it worked perfectly. Maybe it was because of the settings in the shared hosting. 

Thanks for the response.
Rudy

**Comment by soonick** [comment]
Thanks for letting us know.
