### ISSUE TITLE
No install- goes right to login

### ISSUE THREAD

**Issue by faltered** [soonick/poMMo#82]
I unzip & loaded Pommo and it keeps taking me right to a login page- not an install page. I see where you point people to an upgrade.sql script but I'm not even sure what to do with that.

I'd appreciate any help you can give me.

**Comment by soonick** [comment]
Hello faltered,

Are you upgrading?

**Comment by faltered** [comment]
No, it's a fresh install.

**Comment by faltered** [comment]
@soonick- I guess the 7th install was the charm- for some reason it finally let me in. Thank you anyway!
