### ISSUE TITLE
Analytics integration in poMMO

### ISSUE THREAD

**Issue by moiseevigor** [soonick/poMMo#83]
The analytics integration in the poMMo interface would be great!
It could be done quite easily I think on the base of this manual. 

http://cutroni.com/blog/2008/11/04/email-tracking-with-google-analytics/

The basic setup for campaign links and you're done. 
Thanks!

**Comment by soonick** [comment]
Hello moiseevigor,

I read the article, but it seems that it only covers tracking of clicked links by adding parameters to the link URLs. This is something that would be done by the person writing the mailing, so poMMo doesn't need to do anything special. 

I am closing this ticket.

Regards,
Adrian

**Comment by moiseevigor** [comment]
Hi Adrian, the post I've referred is done for external services, kind of workaround for one who needs analytics and cannot have it inside the app. But certainly the Email tracking and analytics is the thing that is very requested in pommo (this makes the mailchimp and others certainly rule the market only having this feature ;) I meant that this approach could be used to start integrating google-analytics or any other OSS analytics software with pommo.

**Comment by espellcaste** [comment]
Agree!

**Comment by mayur333** [comment]
@moiseevigor  Agree to you. Pommo is nice for sending bulk mails. if mail tracking functions like google analytics are added / integrated to pommo then it will become very popular. Really needed stuff in pommo.
