### ISSUE TITLE
unpersonalized e-mail wouldn't send

### ISSUE THREAD

**Issue by msd101psu** [soonick/poMMo#84]
I pulled the latest files, installed, configured SMTP, tested SMTP, added subscribers, and sent a mailing without any personalization.  The processing page kept spawning forever without sending any messages.  I went through the code and commented out line 326 in Pommo_Mta.php.  After that the mailing sent successfully.

**Comment by soonick** [comment]
Thanks for reporting this issue and providing a workaround. I will investigate what is happening and if the line is really not necessary and close this ticket when I figure out.
