### ISSUE TITLE
Warning: Invalid argument

### ISSUE THREAD

**Issue by msd101psu** [soonick/poMMo#85]
On the default subscription form I get;

Warning: Invalid argument supplied for foreach() in themes\default\subscribe\form.subscribe.php on line 34

when I don't have any subscriber fields defined, or if all fields are hidden.  I added;

if (isset($this->fields)) {

above line 34, which eliminated the warning.

**Comment by soonick** [comment]
Hello,

Thanks a lot for reporting this issue and how to fix it. I am a little busy right now but I will try to commit the fix on Monday or Tuesday.

Thanks,
Adrian
