### ISSUE TITLE
Upload Images to use in editor

### ISSUE THREAD

**Issue by krazykelv** [soonick/poMMo#87]
I'm thinking of implementing a feature to upload images using ckeditor so that they can be used in newsletters sent out.  Just thought I'd make an issue here and get any feedback on that.

I noticed opencart has a nice image uploader for ckeditor so I think I could just port that one to pommo, because it's also open source so that's ok right?

I'm thinking I'd create a new folder similar to attachments called mailing_images and then create web links to the images in that folder.

**Comment by soonick** [comment]
Hello krazykelv,

Are you working on this feature?

Regards,
Adrian

**Comment by krazykelv** [comment]
Hi Adrian

I am planning to, but will probably only get round to it in a month or two
because there's some other things I have prioritised before this.

Kelvin

**Comment by soonick** [comment]
Good enough ;)

**Comment by soonick** [comment]
This feature has been added
