### ISSUE TITLE
General Issues with 4b44255

### ISSUE THREAD

**Issue by llynix** [soonick/poMMo#9]
We've been using poMMo for a couple years now in our in house mailing program.  It has served us well but is getting buggier and buggier as we add more and more emails.

I tried soonicks poMMo last mailing and the results weren't good.  Here is what I ran into:

Some documentation issues.  First.. read readme.. which said to look in docs directory.  Then I opened up the readme there.. which seemed out of date.  I then noticed an index.php which redirected to a non-existent admin page.

other files in docs seem equally out of date.  This is all there is.. no installation instructions.

I installed all this in directory spommo  (my original directory was pommo)

So I try pointing at spommo/install.php  that causes an error.

So I try just pointing at soonicks/  this leads to database information.

From there things are easy.. add in my database info for the db I created and off I go.

I noticed the databases were identical.  Therefore patching my old version of pommo should simply be a matter of replacing files.

Please keep this in mind as you do any database changes.  These changes will have to be patched for the people who have poMMo in production.

So I installed spommo on my production server.  Droped in the config.php file and tried to use it.

Ok.. tried to import.  Subscriber pages leads to 404:
http://www2.buydentalequipment.com/spommo/admin//spommo/import_txt.php 
In addition changing to csv file import also causes 404.

This is how I start my mailings, by importing the addresses I have gathered since the last one.  So no go here.  I went back to my original code and imported.

Then I sent the mailing.  All seemed good although the status messages seemed to be throwing a lot more of them repeated then it used to.  Just an observation.  But then I was thinking about these broken links.. and wondering if the unsubscribe worked.

I checked the unsubscribe on my test message:

unsubscribe seems to be 404:
http://www2.buydentalequipment.com/spommo/update.php?email=ataylor@dentalplanet.com&code=c208d9c934c62bf6a46110709b16663f

At this point I immediately stopped the mailing.. shut down my spommo.. and continued the mailing from my normal pommo directory.  

It appears I only had a few hundred go out with bad unsubscribe links.  the other 30k should be good judging by the amount of unsubs I received.

Anyway.. that was my first go at using soonicks pommo.  Sorry for the bad news.

I will try to look into some of these bugs but I'm totally lost as to how to submit patches to git.  I'd like to at least submit some installation / upgrade instructions and mark old docs as such.

If anyone knows of an easy tutorial on how to submit a simple patch to a project please point me in the right direction.

**Comment by soonick** [comment]
Hello llynix,

Thank you for taking the time to leave all this feedback. This will help us a lot to make pommo better.

I will create a separate bug report for each of the bugs you mentioned in your message:
- Documentation out of date
- Contacts importation
- Unsubscribe link in mailings

I will have in mind old users when making changes to the database, If something important changes I will give detailed instructions (or a tool) to move from one database to the other.

Submiting patches is really very easy. You just need to form my project, make the changes in your version. Then commit. And finally click on the "pull request" button and I will be notified that you have changes to merge.

Thank you very much.

Adrian Ancona Novelo.
