### ISSUE TITLE
non-latin characters in input fields get garbled

### ISSUE THREAD

**Issue by baltuonis** [soonick/poMMo#94]
poMMo has problems with non-latin characters input.
encoding is utf8
mysql encoding utf8
all records in mysql seems to be fine

If i save non-latin characters - input fields get garbled.
If I save garbled input fields again (no edit), then records gets garbled.

![Input-field-screenshot](http://s3.kkloud.com/gett/10mckMP/Capture.PNG.0x675.iy2694yd54d6ajor7iazcelk7fei2j4i.png)

**Comment by mafrez** [comment]
Hi, I had the same problem and it was because of string encoding. Just change in code
echo htmlentities($somevariable);
TO
echo htmlentities($somevariable, ENT_NOQUOTES, 'UTF-8');

**Comment by soonick** [comment]
Thanks.

I will implement the fix as soon as I can reproduce the issue.

**Comment by soonick** [comment]
Hello,

Can you please give me some more information of how to reproduce. I don't see the problem in my server.

Thanks,
Adrian

**Comment by gsmtools** [comment]
Hello,

I have exactly the same problem.
fresh installation
MySQL encoding is UTF-8
all is set to UTF-8

I fill this:
http://inzerce2.cz/x/pommo.jpg

after I click on continue and then click on setup again I can see this
http://inzerce2.cz/x/pommo2.jpg

what is wrong?
can you repair this bug or tell me what should be wrong on my side?

Thanks

Jan

**Comment by gsmtools** [comment]
another screen
http://inzerce2.cz/x/pommo3.jpg

all mails has damaged non-latin charactes :-(

**Comment by gsmtools** [comment]
update:
when I am not returning back to setup or compose, preview is ok, all mails are send correctly
attachments, encoding, all is well

when I click back to setup or compose, encoding in preview is damaged and attachement is missing

**Comment by soonick** [comment]
Hello Jan,

I followed your steps to reproduce but for some reason it is not failing for me.  If you can give me the output of phpinfo() on your server it would help me find out what the issue is.

Regards,
Adrian

**Comment by gsmtools** [comment]
Configure Command    './configure' '--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--target=x86_64-redhat-linux-gnu' '--program-prefix=' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/usr/com' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--cache-file=../config.cache' '--with-libdir=lib64' '--with-config-file-path=/etc' '--with-config-file-scan-dir=/etc/php.d' '--disable-debug' '--with-pic' '--disable-rpath' '--without-pear' '--with-bz2' '--with-exec-dir=/usr/bin' '--with-freetype-dir=/usr' '--with-png-dir=/usr' '--with-xpm-dir=/usr' '--enable-gd-native-ttf' '--with-t1lib=/usr' '--without-gdbm' '--with-gettext' '--with-gmp' '--with-iconv' '--with-jpeg-dir=/usr' '--with-openssl' '--with-zlib' '--with-layout=GNU' '--enable-exif' '--enable-ftp' '--enable-magic-quotes' '--enable-sockets' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--with-kerberos' '--enable-ucd-snmp-hack' '--enable-shmop' '--enable-calendar' '--with-libxml-dir=/usr' '--enable-xml' '--with-system-tzdata' '--with-apxs2=/usr/sbin/apxs' '--without-mysql' '--without-gd' '--disable-dom' '--disable-dba' '--without-unixODBC' '--disable-pdo' '--disable-xmlreader' '--disable-xmlwriter' '--without-sqlite' '--without-sqlite3' '--disable-phar' '--disable-fileinfo' '--disable-json' '--without-pspell' '--disable-wddx' '--without-curl' '--disable-posix' '--disable-sysvmsg' '--disable-sysvshm' '--disable-sysvsem'
Server API  Apache 2.0 Handler
Virtual Directory Support   disabled
Configuration File (php.ini) Path   /etc
Loaded Configuration File   /etc/php.ini
Scan this dir for additional .ini files /etc/php.d
Additional .ini files parsed    /etc/php.d/curl.ini, /etc/php.d/dom.ini, /etc/php.d/fileinfo.ini, /etc/php.d/gd.ini, /etc/php.d/imap.ini, /etc/php.d/ioncube.ini, /etc/php.d/json.ini, /etc/php.d/mbstring.ini, /etc/php.d/mcrypt.ini, /etc/php.d/mysql.ini, /etc/php.d/mysqli.ini, /etc/php.d/pdo.ini, /etc/php.d/pdo_mysql.ini, /etc/php.d/pdo_sqlite.ini, /etc/php.d/phar.ini, /etc/php.d/sqlite.ini, /etc/php.d/wddx.ini, /etc/php.d/xmlreader.ini, /etc/php.d/xmlwriter.ini, /etc/php.d/xsl.ini, /etc/php.d/zip.ini
PHP API 20090626
PHP Extension   20090626
Zend Extension  220090626
Zend Extension Build    API220090626,NTS
PHP Extension Build API20090626,NTS
Debug Build no
Thread Safety   disabled
Zend Memory Manager enabled
Zend Multibyte Support  disabled
IPv6 Support    enabled
Registered PHP Streams  https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports tcp, udp, unix, udg, ssl, sslv3, sslv2, tls
Registered Stream Filters   zlib._, bzip2._, convert.iconv._, string.rot13, string.toupper, string.tolower, string.strip_tags, convert._, consumed, dechunk

This program makes use of the Zend Scripting Language Engine:
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with the ionCube PHP Loader v3.3.17, Copyright (c) 2002-2010, by ionCube Ltd., and
    with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies

Configuration

apache2handler

Apache Version  Apache
Apache API Version  20051115
Server Administrator    root@localhost
User/Group  apache(48)/48
Max Requests    Per Child: 1000 - Keep Alive: on - Max Per Connection: 100
Timeouts    Connection: 120 - Keep-Alive: 1
Virtual Server  Yes
Server Root /etc/httpd
Loaded Modules  core prefork http_core mod_so mod_auth_basic mod_authn_file mod_authn_alias mod_authn_anon mod_authn_default mod_authz_host mod_authz_user mod_authz_owner mod_authz_groupfile mod_authz_default mod_include mod_log_config mod_logio mod_env mod_ext_filter mod_mime_magic mod_expires mod_deflate mod_headers mod_usertrack mod_setenvif mod_mime mod_status mod_autoindex mod_info mod_vhost_alias mod_negotiation mod_dir mod_actions mod_speling mod_userdir mod_alias mod_rewrite mod_cache mod_suexec mod_disk_cache mod_file_cache mod_mem_cache mod_cgi mod_version mod_php5 mod_ssl

Directive   Local Value Master Value
engine  1   1
last_modified   0   0
xbithack    0   0

Connection  keep-alive
User-Agent  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/22.0.1229.94 Safari/537.4
Accept  text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Encoding gzip,deflate,sdch
Accept-Language cs-CZ,cs;q=0.8
Accept-Charset  windows-1250,utf-8;q=0.7,*;q=0.3
HTTP Response Headers
Keep-Alive  timeout=1, max=100
Connection  Keep-Alive
Transfer-Encoding   chunked
Content-Type    text/html

bz2

BZip2 Support   Enabled
Stream Wrapper support  compress.bz2://
Stream Filter support   bzip2.decompress, bzip2.compress
BZip2 Version   1.0.3, 15-Feb-2005

calendar

Calendar support    enabled

Core

PHP Version 5.3.2

Directive   Local Value Master Value
allow_call_time_pass_reference  Off Off
allow_url_fopen On  On
allow_url_include   Off Off
always_populate_raw_post_data   Off Off
arg_separator.input &   &
arg_separator.output    &   &
asp_tags    Off Off
auto_append_file    no value    no value
auto_globals_jit    On  On
auto_prepend_file   no value    no value
browscap    no value    no value
default_charset no value    no value
default_mimetype    text/html   text/html
define_syslog_variables Off Off
disable_classes no value    no value
disable_functions   no value    no value
display_errors  Off Off
display_startup_errors  Off Off
doc_root    no value    no value
docref_ext  no value    no value
docref_root no value    no value
enable_dl   Off Off
error_append_string no value    no value
error_log   no value    no value
error_prepend_string    no value    no value
error_reporting 22519   22519
exit_on_timeout Off Off
expose_php  Off Off
extension_dir   /usr/lib64/php/modules  /usr/lib64/php/modules
file_uploads    On  On
highlight.bg    #FFFFFF #FFFFFF
highlight.comment   #FF8000 #FF8000
highlight.default   #0000BB #0000BB
highlight.html  #000000 #000000
highlight.keyword   #007700 #007700
highlight.string    #DD0000 #DD0000
html_errors Off Off
ignore_repeated_errors  Off Off
ignore_repeated_source  Off Off
ignore_user_abort   Off Off
implicit_flush  Off Off
include_path    .:/usr/share/pear:/usr/share/php    .:/usr/share/pear:/usr/share/php
log_errors  On  On
log_errors_max_len  1024    1024
magic_quotes_gpc    Off Off
magic_quotes_runtime    Off Off
magic_quotes_sybase Off Off
mail.add_x_header   Off Off
mail.force_extra_parameters no value    no value
mail.log    /var/log/phpmail    /var/log/phpmail
max_execution_time  30  30
max_file_uploads    20  20
max_input_nesting_level 64  64
max_input_time  60  60
memory_limit    128M    128M
open_basedir    no value    no value
output_buffering    4096    4096
output_handler  no value    no value
post_max_size   16M 16M
precision   14  14
realpath_cache_size 16K 16K
realpath_cache_ttl  120 120
register_argc_argv  Off Off
register_globals    Off Off
register_long_arrays    Off Off
report_memleaks On  On
report_zend_debug   On  On
request_order   GP  GP
safe_mode   Off Off
safe_mode_exec_dir  no value    no value
safe_mode_gid   Off Off
safe_mode_include_dir   no value    no value
sendmail_from   no value    no value
sendmail_path   /usr/sbin/sendmail -t -i    /usr/sbin/sendmail -t -i
serialize_precision 100 100
short_open_tag  On  On
SMTP    localhost   localhost
smtp_port   25  25
sql.safe_mode   Off Off
track_errors    Off Off
unserialize_callback_func   no value    no value
upload_max_filesize 16M 16M
upload_tmp_dir  no value    no value
user_dir    no value    no value
user_ini.cache_ttl  300 300
user_ini.filename   .user.ini   .user.ini
variables_order GPCS    GPCS
xmlrpc_error_number 0   0
xmlrpc_errors   Off Off
y2k_compliance  On  On
zend.enable_gc  On  On

ctype

ctype functions enabled

curl

cURL support    enabled
cURL Information    7.15.5
Age 2
Features
AsynchDNS   No
Debug   No
GSS-Negotiate   Yes
IDN Yes
IPv6    Yes
Largefile   Yes
NTLM    Yes
SPNEGO  No
SSL Yes
SSPI    No
krb4    No
libz    Yes
CharConv    No
Protocols   tftp, ftp, telnet, dict, ldap, http, file, https, ftps
Host    x86_64-redhat-linux-gnu
SSL Version  OpenSSL/0.9.8b
ZLib Version    1.2.3

date

date/time support   enabled
"Olson" Timezone Database Version   0.system
Timezone Database   internal
Default timezone    Europe/Prague

Directive   Local Value Master Value
date.default_latitude   31.7667 31.7667
date.default_longitude  35.2333 35.2333
date.sunrise_zenith 90.583333   90.583333
date.sunset_zenith  90.583333   90.583333
date.timezone   Europe/Prague   Europe/Prague

dom

DOM/XML enabled
DOM/XML API Version 20031129
libxml Version  2.6.26
HTML Support    enabled
XPath Support   enabled
XPointer Support    enabled
Schema Support  enabled
RelaxNG Support enabled

ereg

Regex Library   Bundled library enabled

exif

EXIF Support    enabled
EXIF Version    1.4 $Id: exif.c 293036 2010-01-03 09:23:27Z sebastian $
Supported EXIF Version  0220
Supported filetypes JPEG,TIFF

Directive   Local Value Master Value
exif.decode_jis_intel   JIS JIS
exif.decode_jis_motorola    JIS JIS
exif.decode_unicode_intel   UCS-2LE UCS-2LE
exif.decode_unicode_motorola    UCS-2BE UCS-2BE
exif.encode_jis no value    no value
exif.encode_unicode ISO-8859-15 ISO-8859-15

fileinfo

fileinfo support    enabled
version 1.0.5-dev

filter

Input Validation and Filtering  enabled
Revision    $Revision: 294106 $

Directive   Local Value Master Value
filter.default  unsafe_raw  unsafe_raw
filter.default_flags    no value    no value

ftp

FTP support enabled

gd

GD Support  enabled
GD Version  bundled (2.0.34 compatible)
FreeType Support    enabled
FreeType Linkage    with freetype
FreeType Version    2.2.1
T1Lib Support   enabled
GIF Read Support    enabled
GIF Create Support  enabled
JPEG Support    enabled
libJPEG Version 6b
PNG Support enabled
libPNG Version  1.2.10
WBMP Support    enabled
XPM Support enabled
XBM Support enabled

Directive   Local Value Master Value
gd.jpeg_ignore_warning  0   0

gettext

GetText Support enabled

gmp

gmp support enabled
GMP version 4.1.4

hash

hash support    enabled
Hashing Engines md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost adler32 crc32 crc32b salsa10 salsa20 haval128,3 haval160,3 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5

iconv

iconv support   enabled
iconv implementation    glibc
iconv library version   2.5

Directive   Local Value Master Value
iconv.input_encoding    ISO-8859-1  ISO-8859-1
iconv.internal_encoding ISO-8859-1  ISO-8859-1
iconv.output_encoding   ISO-8859-1  ISO-8859-1

imap

IMAP c-Client Version   2004
SSL Support enabled
Kerberos Support    enabled

json

json support    enabled
json version    1.2.1

libxml

libXML support  active
libXML Compiled Version 2.6.26
libXML Loaded Version   20626
libXML streams  enabled

mbstring

Multibyte Support   enabled
Multibyte string engine libmbfl
HTTP input encoding translation disabled

mbstring extension makes use of "streamable kanji code filter and converter", which is distributed under the GNU Lesser General Public License version 2.1.

Multibyte (japanese) regex support  enabled
Multibyte regex (oniguruma) backtrack check On
Multibyte regex (oniguruma) version 4.7.1

Directive   Local Value Master Value
mbstring.detect_order   no value    no value
mbstring.encoding_translation   Off Off
mbstring.func_overload  0   0
mbstring.http_input pass    pass
mbstring.http_output    pass    pass
mbstring.http_output_conv_mimetypes ^(text/|application/xhtml+xml) ^(text/|application/xhtml+xml)
mbstring.internal_encoding  no value    no value
mbstring.language   neutral neutral
mbstring.strict_detection   Off Off
mbstring.substitute_character   no value    no value

mcrypt

mcrypt support  enabled
Version 2.5.7
Api No  20021217
Supported ciphers   cast-128 gost rijndael-128 twofish arcfour cast-256 loki97 rijndael-192 saferplus wake blowfish-compat des rijndael-256 serpent xtea blowfish enigma rc2 tripledes
Supported modes cbc cfb ctr ecb ncfb nofb ofb stream

Directive   Local Value Master Value
mcrypt.algorithms_dir   no value    no value
mcrypt.modes_dir    no value    no value

mysql

MySQL Support   enabled
Active Persistent Links 0
Active Links    0
Client API version  5.1.46
MYSQL_MODULE_TYPE   external
MYSQL_SOCKET    /var/lib/mysql/mysql.sock
MYSQL_INCLUDE   -I/usr/include/mysql
MYSQL_LIBS  -L/usr/lib64/mysql -lmysqlclient

Directive   Local Value Master Value
mysql.allow_local_infile    On  On
mysql.allow_persistent  Off Off
mysql.connect_timeout   60  60
mysql.default_host  no value    no value
mysql.default_password  no value    no value
mysql.default_port  no value    no value
mysql.default_socket    /var/lib/mysql/mysql.sock   /var/lib/mysql/mysql.sock
mysql.default_user  no value    no value
mysql.max_links Unlimited   Unlimited
mysql.max_persistent    Unlimited   Unlimited
mysql.trace_mode    Off Off

mysqli

MysqlI Support  enabled
Client API library version  5.1.46
Active Persistent Links 0
Inactive Persistent Links   0
Active Links    0
Client API header version   5.1.44
MYSQLI_SOCKET   /var/lib/mysql/mysql.sock

Directive   Local Value Master Value
mysqli.allow_local_infile   On  On
mysqli.allow_persistent On  On
mysqli.default_host no value    no value
mysqli.default_port 3306    3306
mysqli.default_pw   no value    no value
mysqli.default_socket   no value    no value
mysqli.default_user no value    no value
mysqli.max_links    Unlimited   Unlimited
mysqli.max_persistent   Unlimited   Unlimited
mysqli.reconnect    Off Off

openssl

OpenSSL support enabled
OpenSSL Library Version OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
OpenSSL Header Version  OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

pcre

PCRE (Perl Compatible Regular Expressions) Support  enabled
PCRE Library Version    8.00 2009-10-19

Directive   Local Value Master Value
pcre.backtrack_limit    100000  100000
pcre.recursion_limit    100000  100000

PDO

PDO support enabled
PDO drivers mysql, sqlite, sqlite2

pdo_mysql

PDO Driver for MySQL    enabled
Client API version  5.1.46

pdo_sqlite

PDO Driver for SQLite 3.x   enabled
SQLite Library  3.3.6

Phar

Phar: PHP Archive support   enabled
Phar EXT version    2.0.1
Phar API version    1.1.1
SVN revision    $Revision: 290435 $
Phar-based phar archives    enabled
Tar-based phar archives enabled
ZIP-based phar archives enabled
gzip compression    enabled
bzip2 compression   enabled
Native OpenSSL support  enabled

Phar based on pear/PHP_Archive, original concept by Davey Shafik.
Phar fully realized by Gregory Beaver and Marcus Boerger.
Portions of tar implementation Copyright (c) 2003-2009 Tim Kientzle.

Directive   Local Value Master Value
phar.cache_list no value    no value
phar.readonly   On  On
phar.require_hash   On  On

Reflection

Reflection  enabled
Version $Revision: 293036 $

session

Session Support enabled
Registered save handlers    files user sqlite
Registered serializer handlers  php php_binary wddx

Directive   Local Value Master Value
session.auto_start  Off Off
session.bug_compat_42   Off Off
session.bug_compat_warn Off Off
session.cache_expire    180 180
session.cache_limiter   nocache nocache
session.cookie_domain   no value    no value
session.cookie_httponly Off Off
session.cookie_lifetime 0   0
session.cookie_path /   /
session.cookie_secure   Off Off
session.entropy_file    no value    no value
session.entropy_length  0   0
session.gc_divisor  1000    1000
session.gc_maxlifetime  1440    1440
session.gc_probability  1   1
session.hash_bits_per_character 5   5
session.hash_function   0   0
session.name    PHPSESSID   PHPSESSID
session.referer_check   no value    no value
session.save_handler    files   files
session.save_path   /var/lib/php/session    /var/lib/php/session
session.serialize_handler   php php
session.use_cookies On  On
session.use_only_cookies    On  On
session.use_trans_sid   0   0

shmop

shmop support   enabled

SimpleXML

Simplexml support   enabled
Revision    $Revision: 293036 $
Schema support  enabled

sockets

Sockets Support enabled

SPL

SPL support enabled
Interfaces  Countable, OuterIterator, RecursiveIterator, SeekableIterator, SplObserver, SplSubject
Classes AppendIterator, ArrayIterator, ArrayObject, BadFunctionCallException, BadMethodCallException, CachingIterator, DirectoryIterator, DomainException, EmptyIterator, FilesystemIterator, FilterIterator, GlobIterator, InfiniteIterator, InvalidArgumentException, IteratorIterator, LengthException, LimitIterator, LogicException, MultipleIterator, NoRewindIterator, OutOfBoundsException, OutOfRangeException, OverflowException, ParentIterator, RangeException, RecursiveArrayIterator, RecursiveCachingIterator, RecursiveDirectoryIterator, RecursiveFilterIterator, RecursiveIteratorIterator, RecursiveRegexIterator, RecursiveTreeIterator, RegexIterator, RuntimeException, SplDoublyLinkedList, SplFileInfo, SplFileObject, SplFixedArray, SplHeap, SplMinHeap, SplMaxHeap, SplObjectStorage, SplPriorityQueue, SplQueue, SplStack, SplTempFileObject, UnderflowException, UnexpectedValueException

SQLite

SQLite support  enabled
PECL Module version 2.0-dev $Id: sqlite.c 293036 2010-01-03 09:23:27Z sebastian $
SQLite Library  2.8.17
SQLite Encoding UTF-8

Directive   Local Value Master Value
sqlite.assoc_case   0   0

standard

Dynamic Library Support enabled
Path to sendmail    /usr/sbin/sendmail -t -i

Directive   Local Value Master Value
assert.active   1   1
assert.bail 0   0
assert.callback no value    no value
assert.quiet_eval   0   0
assert.warning  1   1
auto_detect_line_endings    0   0
default_socket_timeout  60  60
safe_mode_allowed_env_vars  PHP_    PHP_
safe_mode_protected_env_vars    LD_LIBRARY_PATH LD_LIBRARY_PATH
url_rewriter.tags   a=href,area=href,frame=src,input=src,form=fakeentry a=href,area=href,frame=src,input=src,form=fakeentry
user_agent  no value    no value

tokenizer

Tokenizer Support   enabled

wddx

WDDX Support    enabled
WDDX Session Serializer enabled

xml

XML Support active
XML Namespace Support   active
libxml2 Version 2.6.26

xmlreader

XMLReader   enabled

xmlwriter

XMLWriter   enabled

xsl

XSL enabled
libxslt Version 1.1.17
libxslt compiled against libxml Version 2.6.26
EXSLT   enabled
libexslt Version    1.1.17

Zend Guard Loader

Zend Guard Loader   enabled
License Path    no value
Obfuscation level   3

zip

Zip enabled
Extension Version   $Id: php_zip.c 294817 2010-02-09 17:51:39Z pajoye $
Zip version 1.9.1
Libzip version  0.9.0

zlib

ZLib Support    enabled
Stream Wrapper support  compress.zlib://
Stream Filter support   zlib.inflate, zlib.deflate
Compiled Version    1.2.3
Linked Version  1.2.3

Directive   Local Value Master Value
zlib.output_compression Off Off
zlib.output_compression_level   -1  -1
zlib.output_handler no value    no value

Additional Modules

Module Name
ionCube Loader

Environment

Variable    Value
TERM    xterm
PATH    /sbin:/usr/sbin:/bin:/usr/bin
PWD /
LANG    C
SHLVL   2
_   /usr/sbin/httpd

**Comment by soonick** [comment]
Hello Jan,

Thanks for the info. It seems like the reason I wasn't able to reproduce was because I was using PHP 5.4. I set up an environment with 5.3 and now I see the problem.

I will take a look and let you know when it is fixed.

Regards,
Adrian

**Comment by gsmtools** [comment]
Hello Adrian,

It will be great if you can fix it as soon as possible :)
I have very similar bug with attachment as I described in another thread.

**Comment by soonick** [comment]
Encoding is ok now except html preview before sending - ajax/mailing_preview.php

**Comment by soonick** [comment]
Hello Jan,

I checked ajax/mailing_preview.php and it is showing all characters correctly for me. Can you please provide the steps you followed to reproduce?

Thanks,
Adrian

**Comment by gsmtools** [comment]
Hello Adrian,

first of all I wrote a subject and html message
http://inzerce2.cz/x/pommo6.jpg

then preview
http://inzerce2.cz/x/pommo7.jpg

then HTML Message : Click Here
http://inzerce2.cz/x/pommo8.jpg

**Comment by soonick** [comment]
Hello Jan,

For some reason I am not getting that problem in any of my configurations (PHP 5.4 or PHP 5.3). Anyway I made a commit that I hope will fix the issue.

Regards,
Adrian

**Comment by latsami** [comment]
Hi,
I have 2 installs of Pommo for 2 different clients. I encountered the same problems.

I first made commit 399999b from above by hand on one install and it worked like a charm.

Then I wanted to work on the other install which was much older. I decided to reclone the project instead. The versions has been updated successfully but the accentuated characters are still fuzzy.

I run PHP 5.3.3-7+squeeze14, mysql table is UTF-8.

Any idea of why it behaves differently?

**Comment by soonick** [comment]
Hello latsami,

These kind of problems are usually a little hard to troubleshoot without access to the server. I would recommend you to take a look at the output of phpinfo() in both configurations and see where they differ.

Let me know if that works.

Regards,
Adrian

**Comment by latsami** [comment]
Hi,
thanks for your tip. The two installs are on the same server; the phpinfo() are similar...

edit: I think it's a db issue. I copied/pasted the install A that worked into the other working directory B. It worked, then I changed the db from A to B in config file, and now it doesn't. Will look into that...

**Comment by latsami** [comment]
Hello, 
I found the culprit. The db was indeed in utf-8, but the columns weren't as it's a rather old db...
Thank you for your time!
