### ISSUE TITLE
Problem after installation: Php mysql module is not installed

### ISSUE THREAD

**Issue by ghost** [soonick/poMMo#95]
Hello,

i have new installed pommo on my webspace and did the online-installation-process.
Now, if i try to login, this line appears: Php mysql module is not installed

What could i do to fix it?

Hope for useful tipps.

estebu

**Comment by micdech** [comment]
It's a problem on your server. not on pommo files. Check your server details, and  try to install php-mysql lib

**Comment by soonick** [comment]
Hello estebu,

Can you please confirm if you have php, mysql and php-mysql installed?

**Comment by ghost** [comment]
For sure - php, mysql and php-mysql is installed!

I have "solved" the problem:  <? phpinfo(INFO_MODULES); ?>  doesn't work on every webspace!!

In    "/lib/Module_Check.php"   pommo wants to check, if module is loaded - so (in my case) the webhoster do not allowing this check (don't allowed to read the php.ini?)  - i've tryed it on my own with uploading an info.php

/*******************************_/
<?php
phpinfo();
?>
/**_****************************/

 but nothing will be listed as i open the info.php (expecting php-version an license
-> see the screenshot: http://www.bilder-upload.eu/show.php?file=de437d-1351863210.jpg) !!

Now i have hard-coded the Module_Check.php (near line 50 below) into: 

/*************************************************************_/
public function isLoaded($moduleName) {
    if($this->Modules[$moduleName]) { 
      return false;
    }
    return true;
  }
/**_**********************************************************/

and it works now. 
Is it possible to fix this? Maybe others have the same problem while installing pommo on a webspace without allowed to read the php.ini ?

Sorry my bad english!

Regards
estebu

**Comment by soonick** [comment]
Hello estebu,

Thanks for all the information. I think I have seen this issue in the past but I wasn't able to reproduce it. I will play with my apache configuration and let you know if I can reproduce and provide a work around.

Regards,
Adrian

**Comment by soonick** [comment]
Hello estebu,

I changed the mysql check to use extension_loaded() instead of phpinfo(). Can you please check it solves the problem for you?

Thanks,
Adrian
