### ISSUE TITLE
Multi-select field?

### ISSUE THREAD

**Issue by dtougas** [soonick/poMMo#96]
Is there a way to make a multi-value field multi-select as well? (Even better would be an array of checkboxes) Or is the only way to do it to right now to do it with a bunch of checkbox fields?

**Comment by soonick** [comment]
Hello dtougas,

Can you give me an example of what you have in mind an a use case?

Thanks,
Adrian

**Comment by dtougas** [comment]
Say I have a mailing list that covers a variety of topics, some of which may interest my users, others which may not. I would like to be able to segment my list based on user interests. It would be nice to be able to create a multi-value field called "Interests" and let users select more than one. Currently, the only way to do that would be to create a separate checkbox for each interest.

**Comment by micdech** [comment]
This is yet possible with add field
Il giorno 02/nov/2012 14:46, "Damien Tougas" notifications@github.com ha
scritto:

**Comment by soonick** [comment]
Hello Dtougas,

So the functionality you are trying to achieve is currently possible with checkboxes?

My concern is the way we would create groups based on  a multi-select, we would have to do something like:
Multi-select contains any or all or these values

Is that what you have in mind?

**Comment by dtougas** [comment]
Ok, so I have decided to go with MailChimp for my mailing list (for a number of reasons), so don't go creating this feature just for me :-)

That being said, the way this feature works in PHPList and MailChimp is as follows: Say I create a multi-value field called Interests (example values might be Pottery, Basket Weaving, and Cooking). The user checks-off their interests. Then I create a group called "People who craft", and I select those users who have the Pottery AND Basket Weaving Interests to be part of the group.

Technically, this can be done using plain checkboxes, creating one for each interest, so I suppose it isn't really a high priority option. I guess it is just a clean way of grouping checkboxes into a single variable. Although a multi-select field cold work too.

**Comment by soonick** [comment]
Hello dtougas,

Thanks a lot for taking the time to explain how this works. I see how this can create a better user experience by requiring less clicks to achieve the same result.

As you said this may not be high priority because there are other ways to achieve the same result but I will leave it in here so we can create it when there is time.

Thanks,
Adrian

**Comment by valerian** [comment]
I think this would be done pretty easily, i might code it in the next few days if my client asks for it.
