### ISSUE TITLE
Mail attachment

### ISSUE THREAD

**Issue by gsmtools** [soonick/poMMo#98]
I can upload attachement without any problem

http://inzerce2.cz/x/pommo4.jpg
attachemnt is in ftp folder
attachment record is in MySQL table as well

when I click on continue and than back to Compose, there are no any attachemnt any more as you can see there
http://inzerce2.cz/x/pommo5.jpg

CentOS5
PHP 5.3.2
MySQL 5.1.46

**Comment by gsmtools** [comment]
update:
I have found that when I upload an attachement and don't go back to the compose, email is send correct with attachments.
When I go back to compose, there are no more any attachemnts
simply there is no way to go back
same with encoding in my case, when I go back, non-latin charactes are bad
I have tested chrome and firefox

**Comment by soonick** [comment]
Thanks for reporting this bug. I will take a look and see what it needs to be done to fix it.

**Comment by gsmtools** [comment]
Hi,
thank you very much for encoding update.
Encoding is ok now except html preview before sending - ajax/mailing_preview.php
email are sending with correct encoding anyway

attachment still gone after reloading compose again
when I don't click back on compose, mails are sending with attachment
when I click back on compose, mails are without attachment

**Comment by gsmtools** [comment]
Hello,

this update unforutunately didn't fix loosing attachemnt when click pack to compose.
But since now I can see correct ajax preview with all non latin characters .
So bug issues/94 - Encoding is ok now except html preview before sending - ajax/mailing_preview.php
it is now OK
thank you
